### PR TITLE
fix(components): set search result item to use an anchor tag

### LINKED ISSUE #5589: Search result links are <li> with href which is not working on Brave (in SSR context I believe)
### What happens?

Image
Searches are returning `<li>` elements with href directly on them. While it seems to work and be supported on Chrome, it isn't on Brave leading to clicking an element just closing the search modal without doing anything.

Also I believe that it could be SSR related but I have no strong clue because it's not working on a Nuxt-based server but this playground seems to work https://codepen.io/scalarorg/pen/VwOXqam

Link to our integration (under Nuxt) https://github.com/kestra-io/docs/pull/2526.
I'm aware of the Nuxt native integration but as don't want to have a raw openapi page I found it easier to use the api-reference Vue module directly

### What did you expect to happen?

Have a `<a>` nested with a proper `href` so that it's supported everywhere and especially in a SSR context?

### OpenAPI Document

_No response_

### PR DESCRIPTION
**Pull request by hwkr**
Semantically it makes more sense for this to be an `<a>` tag and we're managing the aria semantics already with the `role="option"`.

Fixes #5589

**Checklist**

I’ve gone through the following:

- [x] I’ve added an explanation _why_ this change is needed.
- [x] I’ve added a changeset (`pnpm changeset`).
- [ ] I’ve added tests for the regression or new feature.
- [x] I’ve updated the documentation.

### CODE REVIEW

File: packages/components/src/components/ScalarSearchResults/ScalarSearchResultItem.vue [hunk 1]
```diff
@@ -12,9 +12,10 @@ defineOptions({ inheritAttrs: false })
 const { cx } = useBindCx()
 </script>
 <template>
-  <li
+  <a
```
Comment (antlio) [inline packages/components/src/components/ScalarSearchResults/ScalarSearchResultItem.vue:15]: would set `a` within `li` vs replace it achieve the same? so it keeps the ul > li markup relationship

**Review by marclave — APPROVED** [review]

File: packages/components/src/components/ScalarSearchResults/ScalarSearchResultItem.vue (hunk 1 above)
Comment (hwkr) [reply packages/components/src/components/ScalarSearchResults/ScalarSearchResultItem.vue:15]: Updated!

Comment (antlio) [reply packages/components/src/components/ScalarSearchResults/ScalarSearchResultItem.vue:15]: yes make sense! was just a nit pick but not against ul > div then!

**Review by antlio — APPROVED** [review]
let's go

**Comment by brian-mulier-p** [comment]
Thanks a lot for tackling this :+1:
