### PR TITLE
fix(api-reference): base url variables DOC-2476

### LINKED ISSUE #3697: variables in the server URL don’t use the default values
This (@scalar/galaxy) breaks the code examples:

image
image

### PR DESCRIPTION
**Pull request by antlio**
this pr fixes #3697 by setting default server variable and enhancing empty variable value as seen below:

**⊢ base url before / after**
image
image

**⊢ request example before / after**
image
image

### CODE REVIEW

File: packages/api-reference/src/legacy/helpers/getUrlFromServerState.ts [hunk 1]
```diff
@@ -18,5 +18,18 @@
       ? replaceVariables(server?.url, state.variables)
       : server?.url
 
-  return url
+  // {id} -> __ID__
+  const urlVariables = url?.match(/{(.*?)}/g)
```
[the remark this answers is not in the document]
Comment (antlio) [reply packages/api-reference/src/legacy/helpers/getUrlFromServerState.ts]: should we also update the one from getRequestFromOperation.ts? could refactor and use the findVariables helper too

File: packages/api-reference/src/features/BaseUrl/ServerVariablesSelect.vue [hunk 2]
```diff
@@ -36,9 +36,9 @@ const selected = computed<ScalarListboxOption | undefined>({
       class="variable-select"
       fullWidth
       variant="ghost">
-      <span>
+      <span :class="{ 'text-c-1': value }">
         <span class="sr-only">Selected:</span>
```
Comment (hwkr) [inline packages/api-reference/src/features/BaseUrl/ServerVariablesSelect.vue:40]: We can probably hide this screen reader text if `value` isn't set, otherwise it will read "Selected: Select Value" (and it can probably just say "Select Value")

**Review by hwkr — COMMENTED** [review]
Looks good! Just left one a11y comment :)

File: packages/api-reference/src/features/BaseUrl/ServerVariablesSelect.vue (hunk 2 above)
Comment (antlio) [reply packages/api-reference/src/features/BaseUrl/ServerVariablesSelect.vue:40]: oh great catch!

File: packages/api-reference/src/helpers/getExampleCode.ts [hunk 3]
```diff
@@ -32,6 +32,11 @@ export async function getExampleCode(
     )
   }
 
+  // Prevent snippet generation if starting by a variable
```
Comment (amritk) [inline packages/api-reference/src/helpers/getExampleCode.ts:35]: oh is this because the variables are not replaced?

**Review by amritk — APPROVED** [review]
Ty for doing this one!

File: packages/api-reference/src/legacy/helpers/getUrlFromServerState.ts (hunk 1 above)
[the remark this answers is not in the document]
Comment (hanspagel) [reply packages/api-reference/src/legacy/helpers/getUrlFromServerState.ts]: Yes!

File: packages/api-reference/src/helpers/getExampleCode.ts (hunk 3 above)
Comment (hanspagel) [reply packages/api-reference/src/helpers/getExampleCode.ts:35]: yeah, it throws an error when an url doesn’t have a valid protocol

**Review by hanspagel — CHANGES_REQUESTED** [review]
didn’t review, but spotted this on the screenshot. the select should have the default value selected (https).

Screenshot 2024-11-07 at 20 42 37

**Review by hanspagel — CHANGES_REQUESTED** [review]
Damn, I don’t know why but for some reason it doesn’t change the base URL in the modal anymore.

Screenshot 2024-11-11 at 15 06 57
Screenshot 2024-11-11 at 15 06 59

**Comment by antlio** [comment]
> Damn, I don’t know why but for some reason it doesn’t change the base URL in the modal anymore.
> 
 great catch, it was a close call 😄 now went with returning both origin and modified url so we can display the right one in client on change, while keep displaying the updated one in the reference
