### PR TITLE
fix(api-reference): do not trigger send request unless modal is open

### LINKED ISSUE #8090: Scalar fetches endpoint on every Enter keypress
### What happens?

Whenever you press `Enter` on Scalar's main window, Scalar performs a request on the first endpoint listed in the `paths` section of the spec file.

This can be reproduced in any browser and any spec file, for example, the very basic [HTML/JS sample file](https://scalar.com/products/api-references/integrations/html-js).

Image

This is very undesirable, especially if you have other input fields or forms on the page. Each `Enter` keypress will then silently call an API endpoint.

### What did you expect to happen?

No API calls should be performed on `Enter`, instead, the default browser behavior should apply.

### PR DESCRIPTION
**Pull request by amritk**
## Problem

closes #8090

We were sending request any time you hit enter on the references.

## Solution

- we ensure its meta + enter
- we don't trigger it when the modal is closed

## Checklist

- [x] I explained why the change is needed.
- [x] I added a changeset. 
- [x] I added tests.
- [ ] I updated the documentation.

---

> [!NOTE]
> **Low Risk**
> Behavior change is limited to UI hotkey routing and request triggering, with added tests and no changes to request construction or transport.
> 
> **Overview**
> Prevents global hotkeys from unintentionally sending API requests when the API client modal is not open.
> 
> Hotkey handling is tightened so configured hotkeys only fire when their required modifiers are pressed (e.g., *default modifier + Enter*), and `OperationBlock` now guards `operation:send:request:hotkey` execution in `modal` layout using a new `isModalOpen` prop that is wired from `Modal` through `Operation`. Tests were added/updated to cover the new hotkey and modal-open behavior, and a patch changeset was included for `@scalar/api-client`.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 6e88fbbc8c8735fe7ba8cfdd3143a6a3de2f0a88. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: packages/api-client/src/v2/blocks/operation-block/OperationBlock.vue [hunk 1]
```diff
@@ -255,12 +259,21 @@ const handleExecute = async () => {
   request.value = sendResult.request
 }
 
+/** Guard hotkey execution so closed modal instances do not react to global hotkeys. */
```
Comment (DemonHa) [inline packages/api-client/src/v2/blocks/operation-block/OperationBlock.vue:262]: we should probably do the same for any modal that gets open
