### PR TITLE
fix(api-reference): hideModels not applying on modal close

### LINKED ISSUE #8053: Models hidden, but gets visible after test modal is closed.
### What happens?

.NET core (v10) application with `.HideModels()` enabled. "Models" are hidden in the UI on initial load in the menu. When an API endpoint test is ran and the modal window is closed, the "Models" section get enabled / visible in the menu.

```csharp
app.MapScalarApiReference(options =>
{
	options.WithTitle("Fuel | Scout")
		.AddPreferredSecuritySchemes(ApiKeyAuthHandler.SchemeName)
		.EnablePersistentAuthentication()
		.ExpandAllTags()
		.HideModels()
		.PreserveSchemaPropertyOrder()
		.WithTheme(ScalarTheme.Laserwave);
});
```

### What did you expect to happen?

That they stay hidden as they used to. I can't really show it in the sandbox below, since models are enabled there by default.

### OpenAPI Document

https://sandbox.scalar.com/e/eekNc

### PR DESCRIPTION
**Pull request by amritk**
## Problem
closes #8053

This code is no longer needed with the other fix.

## Checklist

- [x] I explained why the change is needed.
- [x] I added a changeset. 
- [ ] I added tests.
- [ ] I updated the documentation.

---

> [!NOTE]
> **Low Risk**
> Small UI filtering change limited to how model nav items are excluded; low blast radius aside from potential over-matching of IDs that coincidentally end with `models`.
> 
> **Overview**
> Ensures the `hideModels` configuration reliably hides model sections by changing sidebar filtering from an exact `id === 'models'` check to an `id.endsWith('models')` match, covering cases where document reloads/prefixing alter the item IDs.
> 
> Adds a patch changeset for `@scalar/api-reference` documenting the fix.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 51db57ff7d13e32c819ca0d161ba53d6e73dd7e6. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: packages/api-reference/src/components/ApiReference.vue [hunk 1]
```diff
@@ -378,7 +378,7 @@ const sidebarItems = computed<TraversedEntry[]>(() => {
   }
 
   return docItems.filter((item) =>
-    config.hideModels ? item.id !== 'models' : true,
+    config.hideModels ? item.type !== 'models' && item.type !== 'model' : true,
```
Comment (DemonHa) [inline packages/api-reference/src/components/ApiReference.vue]: Just checking the type here should work fine

**Comment by hanspagel** [comment]
cool
