### PR TITLE
fix(api-reference): proxy is skipped for localhost, even if the proxy is local

### LINKED ISSUE #5258: Make Proxy usable in local environments
### Discussed in https://github.com/scalar/scalar/discussions/5257

<div type='discussions-op-text'>

<sup>Originally posted by **xC0dex** March 30, 2025</sup>
Currently, the `proxyUrl` will not be used if the current URL is `localhost`. For the Aspire integration, it would be _awesome_ if this would also work for `localhost` URLs. 

**Context:**

Aspire starts multiple services with different ports. Example:

Book API: `https://localhost:55555`
User API:  `https://localhost:55556`
Scalar Aspire Integration: `https://localhost:55557`

Without a proxy, Scalar cannot load the OpenAPI documents or make requests to the APIs because they are running on a different Port. This will cause CORS issues.</div>

### PR DESCRIPTION
**Pull request by hanspagel**
**Problem**

Our API reference can’t fetch OpenAPI documents from other (local) domains, if CORS isn’t set up properly (because we can’t use the remote proxy then).

**Solution**

Initially, I thought we’re just missing something in the fetching logic, turns out: Not really.  BUT two changes:

* The @scalar/api-reference fetching logic is closer to what we do for API requests.
* If the proxyUrl is relative, we’ll use it even for local domains (fixes #5258)

I used the opportunity to streamline the fetching a bit, though:

* Renamed `fetchSpecFromUrl` to `fetchDocument` (we’re talking about documents, not about the standard/specification)
* Updated comments
* Removed the isValidUrl/isRelativeUrl/whatever logic from `useReactiveSpec` and just used `fetchDocument` (to make it work the same in all places)
* Added a few more tests
* Catched a few more exceptions to simplify the usage of the related helpers

**Checklist**

I’ve gone through the following:

- [x] I’ve added an explanation _why_ this change is needed.
- [x] I’ve added a changeset (`pnpm changeset`).
- [x] I’ve added tests for the regression or new feature.
- [ ] I’ve updated the documentation.

### CODE REVIEW

File: packages/oas-utils/src/helpers/redirect-to-proxy.ts [hunk 1]
```diff
@@ -1,25 +1,37 @@
...
-  }
+  try {
+    if (!shouldUseProxy(proxy, url)) {
+      return url ?? ''
+    }
 
-  // Create new URL object from url
-  const newUrl = new URL(url as string)
+    // Create new URL object from url
+    const newUrl = new URL(url as string)
```
Comment (amritk) [inline packages/oas-utils/src/helpers/redirect-to-proxy.ts:18]:
```suggestion
    const newUrl = new URL(url)
```
why the type cast here, just do an early return above to check for undefined

Comment (amritk) [reply packages/oas-utils/src/helpers/redirect-to-proxy.ts:18]: actually we can turn `shouldUseProxy` into a type guard for proxy then just check for url

File: packages/oas-utils/src/helpers/redirect-to-proxy.ts [hunk 2]
```diff
@@ -35,22 +47,28 @@ export const isRelativePath = (url: string) => {
...
 
-  // Relative URLs
-  if (isRelativePath(url)) {
-    return false
-  }
+    // Relative URLs
+    if (isRelativePath(url)) {
+      return false
+    }
+
```
Comment (amritk) [inline packages/oas-utils/src/helpers/redirect-to-proxy.ts:64]:
```suggestion
    }

  // Requests to a local proxy
  if (isLocalProxy(proxy) {
    return true
  }

```

**Review by amritk — CHANGES_REQUESTED** [review]
So this doesn't actually fix the issue stated in #5258, I added a dummy function below

File: packages/oas-utils/src/helpers/redirect-to-proxy.ts (hunk 1 above)
Comment (hanspagel) [reply packages/oas-utils/src/helpers/redirect-to-proxy.ts]: ahh, type guarding works for one parameter only, but still a great idea

File: packages/oas-utils/src/helpers/redirect-to-proxy.ts (hunk 2 above)
Comment (amritk) [reply packages/oas-utils/src/helpers/redirect-to-proxy.ts:80]: Yea if its deployed then they should not pass in a localhost proxy. Its only for local dev

Comment (amritk) [reply packages/oas-utils/src/helpers/redirect-to-proxy.ts:80]: why can't we just allow the user to pass it in? If they pass in a localhost on a domain it won't work

**Review by xC0dex — APPROVED** [review]
LGTM. This will work for Aspire

**Comment by hanspagel** [comment]
Waiting for @amritk to re-review here. It’s core functionality, so I don’t want to rush it.

**Comment by hanspagel** [comment]
We won’t need this for the Aspire integration, and I don’t see the use case, but I’ve just added this, too. :v:

**Comment by amritk** [comment]
Its come up a couple times, helpful for local testing!

**Review by amritk — APPROVED** [review]
I don't even need to re-test, code looks 👌🏾
