### PR TITLE
fix(api-reference): onServerChange callback not working

### LINKED ISSUE #6793: Configuration for onServerChange does not fire
### What happens?

I am trying to get the `onServerChange` event to fire (to update auth configuration) but cannot see any change in behavior. I'd expect to see console messages, but don't see anything as it is on `1.35.1`.

My document is formatted as such (not fully complete but should get the point across):

```html
<!doctype html>
<html>
  <head>
    <title>Demo</title>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1" />

  <link rel="stylesheet" href="stylesheets/scalar.css">
  </head>
  <body>
    <header class="custom-header scalar-app">
      <span>Demo</span>
    </header>

    <div id="app"></div>

    <!-- Load the Script -->
    <script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference@1.35.1"></script>

    <!-- Initialize the Scalar API Reference -->
    <script>
      // Server-to-auth configuration mapping
      const serverAuthConfigs = {
        'https://server1.com': {},
        'https://server2.com': {},
      };

      // Store scalar reference for dynamic updates
      let scalarRef;

      // Handler for server changes
      function handleServerChange(serverUrl) {
        const authConfig = serverAuthConfigs[serverUrl];
        console.log('Found auth config:', !!authConfig, authConfig);

        if (authConfig && scalarRef) {
          scalarRef.updateConfig({
            authentication: {
              preferredSecurityScheme: "OAuth2",
              securitySchemes: {
                OAuth2: {
                  flows: {
                    authorizationCode: authConfig
                  }
                }
              }
            }
          });
        } else {
          console.log('Cannot update config - missing authConfig or scalarRef');
        }
      }

      scalarRef = Scalar.createApiReference('#app', {
        theme: "default",
        favicon: 'assets/favicon.png',
        hideClientButton: true,
        onServerChange: (value) => {
          console.log('=== onServerChange callback triggered ===');
        },

        authentication: {
            preferredSecurityScheme: "OAuth2",
            securitySchemes: {
                OAuth2: {
                    flows: {
                        authorizationCode: {}
                    }
                }
            }
        },

        url: '',
        servers: [
          {
            url: 'https://server1.com',
            description: 'Staging',
          },
          {
            url: 'https://server2.com',
            description: 'Production',
          },
        ],
      });
    </script>
  </body>
</html>
```

### What did you expect to happen?

I expected to see console messages logged, I saw nothing.

### OpenAPI Document

_No response_

### PR DESCRIPTION
**Pull request by amritk**
**Problem**

closes #6793 

Currently, the `onServerChange` is disconnected.

**Solution**

With this PR we trigger it on change. We can do it here, or maybe have a specific place for config callbacks. Thoughts?

**Checklist**

I've gone through the following:

- [x] I've added an explanation _why_ this change is needed.
- [x] I've added a changeset (`pnpm changeset`).
- [ ] I've added tests for the regression or new feature.
- [ ] I've updated the documentation.

---

> [!NOTE]
> Wire up onServerChange via workspace store events and pass explicit props in Tag layouts; update hook signature and usage accordingly.
> 
> - **Store events and configuration**:
>   - Update `useWorkspaceStoreEvents(store, root, configuration)` to accept `configuration: ApiReferenceConfiguration` and call `configuration.onServerChange(...)` on `scalar-update-selected-server`.
>   - Pass `selectedConfiguration.value` to `useWorkspaceStoreEvents` from `ApiReferenceWorkspace.vue`.
> - **Components**:
>   - In `components/Content/Tags/Tag.vue`, replace `v-bind="$props"` with explicit prop bindings to `ClassicLayout` and `ModernLayout`.
> - **Changeset**:
>   - Add patch changeset for `@scalar/api-reference` noting the fix.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 20ebac085176ae0082b0f18fa0913fae514a61be. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: packages/api-reference/src/components/Content/Tags/Tag.vue [hunk 1]
```diff
@@ -15,12 +15,16 @@ defineProps<{
...
 <template>
   <template v-if="layout === 'classic'">
-    <ClassicLayout v-bind="$props">
+    <ClassicLayout :tag="tag">
       <slot />
     </ClassicLayout>
   </template>
   <template v-else>
-    <ModernLayout v-bind="$props">
+    <ModernLayout
```
Comment (amritk) [inline packages/api-reference/src/components/Content/Tags/Tag.vue:25]: this was just bugging my terminal with warnings

Comment (hanspagel) [reply packages/api-reference/src/components/Content/Tags/Tag.vue:25]: 👍 👍 👍 👍 👍

**Comment by hanspagel** [comment]
I don’t get why the tests are failing 👀

**Comment by amritk** [comment]
@hanspagel it says cancelled not failed, gunna run again
