### PR TITLE
fix(nuxt): module runtime error, css missing, unknown file extension

### LINKED ISSUE #1453: Nuxt Module Runtime Error
### What happens?

Install plugin via `npx nuxi module add @scalar/nuxt` on fresh install no problems adding module.

* Using bun worspaces
* Without adding module to nuxt.config or any other changes:

`bun run dev` 

[4:22:29 PM]  ERROR  Cannot start nuxt:  Cannot find module '/home/runner/work/scalar/scalar/node_modules/.pnpm/jiti@1.21.0/node_modules/jiti/lib/index.js'

Tried this on both a fresh full nuxt app app and in a layers app same result.

NOTICING...

In the layers and full app where I run the plugin installation the package.json gets the `    "@scalar/nuxt": "^0.0.5",` as dependency BUT the `    "@scalar/api-reference": "^1.21.2",` is stuffed into the root bun workspace package.json.  I tremoved `@scalar/api-reference` and tried to add it to the layers/nuxt3 app in th workspace but got the above error and won't build at all now.

### What did you expect to happen?

Able to run nuxt app with or without module enabled in nuxt.config

### How can we reproduce the issue?

1.  fresh empty folder add a bun workspace package.json to root:
```json
{
  "name": "bun-workspace",
  "private": true,
  "workspaces": [
    "apps/*",
    "layers/*"
  ]
}
```

create 2 folders:  `layers` and `apps`

In the `layers` folder:
* create a nuxt layer app `npx nuxi init -t layer layerapp` and use bun as build tool option
cd to layerapp:
* install scalar`npx nuxi module add @scalar/nuxt`. 
* then `bun run dev`

You should get the same error message.

To test on a full nuxt app you'll need to delete the layerapp becuase you won't be able to install a new app now because a build error from the workspace layerapp scalar module is created.

In the `apps` folder:
* create a nuxt app `npx nuxi init nuxtapp` and use bun as build tool option
cd to nuxtapp:
* install scalar`npx nuxi module add @scalar/nuxt`. 
* then `bun run dev`

### Swagger/OpenAPI Example

_No response_

### LINKED ISSUE #1889: Error and warnings with @scalar/nuxt: "prismjs not default export"
### What happens?

Hi!
I am using Scalar Nuxt and I get errors on the Documentation page, and also warnings in the console

## Setup
- `nuxt` `3.11.2`
- `@scalar/nuxt` `0.0.62`
- `nodejs` `v18.20.1`
- Macbook Pro Apple M3 `14.4`

### Configuration
`nuxt.config.ts`
```json
    scalar: {
        theme: "kepler",
        darkMode: true,
        hideDownloadButton: false,
        metaData: {
            title: "API Documentation by VISOID",
        },
        searchHotKey: "k",
        showSidebar: true,
        pathRouting: {
            basePath: "/docs",
        },
        spec: {
            url: process.env.NUXT_PUBLIC_WEBSITE_URL + "/openapi.json",
        },
    },
```

## Errors
In the browser:
```
The requested module '/_nuxt/node_modules/prismjs/prism.js?v=62d157c9' does not provide an export named 'default'
```

In the Nuxt server console:
```
WARN  Failed to load source map for /Users/malograll/visoid/visoid/node_modules/parse5/dist/index.js.
Error: An error occurred while trying to read the map file at index.js.map
Error: ENOENT: no such file or directory, open '/Users/malograll/visoid/visoid/node_modules/parse5/dist/index.js.map'


 WARN  Failed to load source map for /Users/malograll/visoid/visoid/node_modules/parse5/dist/parser/index.js.
Error: An error occurred while trying to read the map file at index.js.map
Error: ENOENT: no such file or directory, open '/Users/malograll/visoid/visoid/node_modules/parse5/dist/parser/index.js.map'


 WARN  Failed to load source map for /Users/malograll/visoid/visoid/node_modules/parse5/dist/serializer/index.js.
Error: An error occurred while trying to read the map file at index.js.map
Error: ENOENT: no such file or directory, open '/Users/malograll/visoid/visoid/node_modules/parse5/dist/serializer/index.js.map'


 WARN  Failed to load source map for /Users/malograll/visoid/visoid/node_modules/parse5/dist/common/error-codes.js.
Error: An error occurred while trying to read the map file at error-codes.js.map
Error: ENOENT: no such file or directory, open '/Users/malograll/visoid/visoid/node_modules/parse5/dist/common/error-codes.js.map'


 WARN  Failed to load source map for /Users/malograll/visoid/visoid/node_modules/parse5/dist/common/foreign-content.js.
Error: An error occurred while trying to read the map file at foreign-content.js.map
Error: ENOENT: no such file or directory, open '/Users/malograll/visoid/visoid/node_modules/parse5/dist/common/foreign-content.js.map'


 WARN  Failed to load source map for /Users/malograll/visoid/visoid/node_modules/parse5/dist/tree-adapters/default.js.
Error: An error occurred while trying to read the map file at default.js.map
Error: ENOENT: no such file or directory, open '/Users/malograll/visoid/visoid/node_modules/parse5/dist/tree-adapters/default.js.map'


 WARN  Failed to load source map for /Users/malograll/visoid/visoid/node_modules/parse5/dist/common/token.js.
Error: An error occurred while trying to read the map file at token.js.map
Error: ENOENT: no such file or directory, open '/Users/malograll/visoid/visoid/node_modules/parse5/dist/common/token.js.map'


 WARN  Failed to load source map for /Users/malograll/visoid/visoid/node_modules/parse5/dist/common/html.js.
Error: An error occurred while trying to read the map file at html.js.map
Error: ENOENT: no such file or directory, open '/Users/malograll/visoid/visoid/node_modules/parse5/dist/common/html.js.map'


 WARN  Failed to load source map for /Users/malograll/visoid/visoid/node_modules/parse5/dist/tokenizer/index.js.
Error: An error occurred while trying to read the map file at index.js.map
Error: ENOENT: no such file or directory, open '/Users/malograll/visoid/visoid/node_modules/parse5/dist/tokenizer/index.js.map'

 WARN  Failed to load source map for /Users/malograll/visoid/visoid/node_modules/parse5/dist/parser/formatting-element-list.js.
Error: An error occurred while trying to read the map file at formatting-element-list.js.map
Error: ENOENT: no such file or directory, open '/Users/malograll/visoid/visoid/node_modules/parse5/dist/parser/formatting-element-list.js.map'


 WARN  Failed to load source map for /Users/malograll/visoid/visoid/node_modules/parse5/dist/common/unicode.js.
Error: An error occurred while trying to read the map file at unicode.js.map
Error: ENOENT: no such file or directory, open '/Users/malograll/visoid/visoid/node_modules/parse5/dist/common/unicode.js.map'


 WARN  Failed to load source map for /Users/malograll/visoid/visoid/node_modules/parse5/dist/parser/open-element-stack.js.
Error: An error occurred while trying to read the map file at open-element-stack.js.map
Error: ENOENT: no such file or directory, open '/Users/malograll/visoid/visoid/node_modules/parse5/dist/parser/open-element-stack.js.map'


 WARN  Failed to load source map for /Users/malograll/visoid/visoid/node_modules/parse5/dist/common/doctype.js.
Error: An error occurred while trying to read the map file at doctype.js.map
Error: ENOENT: no such file or directory, open '/Users/malograll/visoid/visoid/node_modules/parse5/dist/common/doctype.js.map'


 WARN  Failed to load source map for /Users/malograll/visoid/visoid/node_modules/parse5/dist/tokenizer/preprocessor.js.
Error: An error occurred while trying to read the map file at preprocessor.js.map
Error: ENOENT: no such file or directory, open '/Users/malograll/visoid/visoid/node_modules/parse5/dist/tokenizer/preprocessor.js.map'
```

### What did you expect to happen?

No errors

### How can we reproduce the issue?

Using the configuration above

### OpenAPI Document

_No response_

### LINKED ISSUE #2141: Nuxt: `css` is unknown file extension
### What happens?

While rendering an openapi spec using scalar 0.2.8 in nuxt (3.12.1):

`Unknown file extension ".css" for /workspaces/nimbus/node_modules/@scalar/components/dist/style.css`

(Sorry for being here again 😂 )

### What did you expect to happen?

It should render the spec.

### How can we reproduce the issue?

1. Setup nuxt
2. Add scalar 0.2.8 with its config
3. Access rendered spec url (app links to that page are not working)

### OpenAPI Document

_No response_

### PR DESCRIPTION
**Pull request by amritk**
This should fix all of the current nuxt issues

closes #1453
closes #1889
closes #2141

### CODE REVIEW

File: packages/api-reference/src/components/ApiReferenceLayout.vue [hunk 1]
```diff
@@ -231,11 +231,15 @@ hideModels.value = props.configuration.hideModels ?? false
 useDeprecationWarnings(props.configuration)
 </script>
 <template>
-  <Style>{{
-    getThemeStyles(configuration.theme, {
-      fonts: configuration.withDefaultFonts,
-    })
-  }}</Style>
+  <!-- Beware: This does NOT work in SSR -->
```
Comment (amritk) [inline packages/api-reference/src/components/ApiReferenceLayout.vue:234]: cc @hwkr

**Comment by hanspagel** [comment]
What a PR! 🥵

File: packages/api-reference/src/components/Content/Lazy/Loading.vue [hunk 2]
```diff
@@ -114,7 +114,7 @@ watch(
     }
     // Descriptions
     else {
-      scrollToId(hash.value)
+      if (typeof window !== 'undefined') scrollToId(hash.value)
```
Comment (hanspagel) [inline packages/api-reference/src/components/Content/Lazy/Loading.vue:117]: Should we put this in scrollToId? Because there’s no cse where window if undefined and scrollToId will work.

Comment (amritk) [reply packages/api-reference/src/components/Content/Lazy/Loading.vue:117]: yea I thought about that, but this is nice for catching errors

Comment (amritk) [reply packages/api-reference/src/components/Content/Lazy/Loading.vue:117]: we can do either way!

File: packages/api-reference/src/components/Util/Style.vue [hunk 3]
```diff
@@ -3,6 +3,8 @@
 
   We have to use this to inject stylesheets dynamically into the
   page right now because we can't inject into <head> in SSR
+
+  Warn: this does NOT work on SSR, we shouldn't use this component
```
Comment (hwkr) [inline packages/api-reference/src/components/Util/Style.vue:7]: We can probably remove the comment above that says this is to support SSR since apparently it doesn't work 😅 

I don't really have a strong opinion about how we want to do style injection and support SSR 🤷‍♀️

File: packages/api-reference/src/components/ApiReferenceLayout.vue (hunk 1 above)
Comment (hwkr) [reply packages/api-reference/src/components/ApiReferenceLayout.vue:234]: Tbh I'm not really sure how to fix this, I thought originally @hanspagel did it this way so it _would_ support SSR.

**Comment by amritk** [comment]
Alright I popped this back out of draft, there ARE still hydration mismatch issues. But this PR fixes the module not working at all. We can follow up with hydration mismatch fixes

**Review by marclave — APPROVED** [review]
let's get it in!
