### PR TITLE
fix(api-client): request table tooltip

### LINKED ISSUE #4418: The header parameter does not appear in the ui
### What happens?

The header parameter is not visible when trying to send a request.

image

image

I'm guessing that the error may be caused by the `Content-Type` being added rigidly because when you click clear the parameter is visible.

You can repeat this with the online editor and paste the json

https://docs.scalar.com/editor

```json
{
  "openapi": "3.0.1",
  "info": {
    "title": "xxxx.Services.xxxx | v1",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://localhost:5218"
    }
  ],
  "paths": {
    "/api/webhooks/xxxx": {
      "post": {
        "tags": [
          "xxxx.Services.xxxx"
        ],
        "parameters": [
          {
            "name": "x-xxxx-signature",
            "in": "header",
            "description": "Custom header for xxxx signature",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    }
  },
  "components": { },
  "tags": [
    {
      "name": "xxxx.Services.xxxx"
    }
  ]
}
```

### What did you expect to happen?

The header parameter is visible and changeable when attempting to send an HTTP request via the UI.

### OpenAPI Document

https://sandbox.scalar.com/e/IcP-z

### PR DESCRIPTION
**Pull request by antlio**
**Problem**
request table tooltip encountering null item is breaking the client as highlighted in #4418 

**Solution**
this pr fixes #4418 #4427 by updating the request table tooltip logic. still works with #4387

| before | after |
| -------|------|
| image | image |
| header parameter is not displayed  | header is displayed along its tooltip accordingly | 

**Checklist**

I’ve gone through the following:

- [x] I’ve added an explanation _why_ this change is needed.
- [x] I’ve added a changeset (`pnpm changeset`).
- [x] I’ve added tests for the regression or new feature.

### CODE REVIEW

**Comment by amritk** [comment]
The issue was using index as a key which 99% of the time is a big no no, so I replaced all the ones I found. eslint rules inc

File: packages/api-client/src/views/Request/RequestSection/RequestTable.vue [hunk 1]
```diff
@@ -8,6 +8,7 @@ import { ScalarButton, ScalarIcon } from '@scalar/components'
 import type { RequestExampleParameter } from '@scalar/oas-utils/entities/spec'
 import { computed } from 'vue'
 
+import { hasItemProperties } from '../libs/request'
```
Comment (hanspagel) [inline packages/api-client/src/views/Request/RequestSection/RequestTable.vue:11]: can we use the @/ alias here?

**Review by hanspagel — APPROVED** [review]
rad

File: packages/api-client/src/views/Request/RequestSection/RequestTable.vue (hunk 1 above)
Comment (amritk) [reply packages/api-client/src/views/Request/RequestSection/RequestTable.vue:11]: only if its needed/used elsewhere. if its only used here then its fine here.

File: packages/api-client/src/views/Request/libs/request.ts [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+export const hasItemProperties = (item: RequestExampleParameter): boolean => {
+  return !!(
+    item.description ||
+    item.type ||
+    item.default ||
+    item.format ||
+    item.minimum ||
+    item.maximum
+  )
+}
```
Comment (amritk) [inline packages/api-client/src/views/Request/libs/request.ts:21]:
```suggestion
export const hasItemProperties = (item: RequestExampleParameter) => 
  Boolean(
    item.description ||
    item.type ||
    item.default ||
    item.format ||
    item.minimum ||
    item.maximum
  )
```
I would write it like this personally but functionally is the same

**Review by amritk — APPROVED** [review]

File: packages/api-client/src/views/Request/libs/request.ts (hunk 2 above)
Comment (antlio) [reply packages/api-client/src/views/Request/libs/request.ts:21]: I agree it's more clear too
