### PR TITLE
fix(api-client): ensure we preserve lowercase authentication headers

### LINKED ISSUE #4763: Latest version of scalar 1.25.118 breaks authentication
### What happens?

Authentication header is no longer passed/sent to server in [1.25.118](https://www.npmjs.com/package/@scalar/api-reference/v/1.25.118) version even if its specified in auth config. This works on [1.25.116](https://www.npmjs.com/package/@scalar/api-reference/v/1.25.116).

### What did you expect to happen?

When authentication is specified, send auth headers as well

### OpenAPI Document

_No response_

### PR DESCRIPTION
**Pull request by amritk**
**Problem**
If you have a lowercase only auth header it will get deleted

**Solution**
Instead of adding and deleting we just lowercase them.

fixes #4763

**Checklist**

I’ve gone through the following:

- [x] I’ve added an explanation _why_ this change is needed.
- [x] I’ve added a changeset (`pnpm changeset`).
- [x] I’ve added tests for the regression or new feature.
- [ ] I’ve updated the documentation.

See the [contributing guide](https://github.com/scalar/scalar/blob/main/CONTRIBUTING.md) for more information.

### CODE REVIEW

File: packages/api-client/src/libs/send-request/create-request-operation.ts [hunk 1]
```diff
@@ -114,13 +114,15 @@ export const createRequestOperation = ({
     const security = buildRequestSecurity(selectedSecuritySchemes, env)
 
     // For securityheaders, we lowercase them so they can be uppercased later (in normalizeHeaders)
-    Object.keys(security.headers).forEach((key) => {
-      security.headers[key.toLowerCase()] = security.headers[key] ?? ''
-      delete security.headers[key]
-    })
+    const normalizedSecurityHeaders = Object.entries(security.headers).reduce<
```
Comment (amritk) [inline packages/api-client/src/libs/send-request/create-request-operation.ts:117]: @marclave sometimes reduce is the way

Comment (marclave) [reply packages/api-client/src/libs/send-request/create-request-operation.ts:117]: mfw i see a reduce

👁️ 👄 👁️

**Review by marclave — APPROVED** [review]
🖖
