### PR TITLE
fix(api-reference): section header long content + classic layout responsive

### LINKED ISSUE #3956: Horizontal overflow in ui.
### What happens?

Horizontal overflow in `@scalar/api-reference` version `1.25.68`.

### What did you expect to happen?

No overflow.

### OpenAPI Document

_No response_

### PR DESCRIPTION
**Pull request by antlio**
this pr fixes #3956 by:
- enhancing section header display with long content
- fixing classic layout responsiveness

**⊢ header before / after**
<div>
image
image 
</div>

**⊢ classic alignment + border before / after**
<div>
image
image
</div>

**⊢ classic mobile before / after**
<div>
image
image
</div>

### CODE REVIEW

File: packages/api-reference/src/components/Anchor/Anchor.vue [hunk 1]
```diff
@@ -37,6 +37,8 @@ const getUrlWithId = (id: string) => {
 .label {
   position: relative;
   display: inline-block;
+  text-align: left;
```
Comment (hwkr) [inline packages/api-reference/src/components/Anchor/Anchor.vue:40]: It's weird this wasn't left already 🤔

File: packages/api-reference/src/components/Content/Content.vue [hunk 2]
```diff
@@ -127,10 +127,14 @@ const introCardsSlot = computed(() =>
 }
 .introduction-card-item {
   padding: 9px;
-  border-bottom: var(--scalar-border-width) solid var(--scalar-border-color);
   display: flex;
   flex-direction: column;
-  justify-content: center;
+  justify-content: start;
+}
+@media (max-width: 900px) {
```
Comment (hwkr) [inline packages/api-reference/src/components/Content/Content.vue:134]: I think this uses a container query elsewhere, @cameronrohani?

See [here](https://github.com/scalar/scalar/blob/main/packages/api-reference/src/components/ClassicHeader.vue#L24) or [here](https://github.com/scalar/scalar/blob/main/packages/api-reference/src/components/Content/Content.vue#L164) and the [container](https://github.com/scalar/scalar/blob/main/packages/api-reference/src/components/Content/Content.vue#L108-L111).

File: packages/api-reference/src/components/Section/SectionHeader.vue [hunk 3]
```diff
@@ -12,17 +12,30 @@ withDefaults(
...
-  <LoadingSkeleton v-if="loading" />
-  <component
-    :is="`h${level}`"
-    v-else
-    class="section-header"
-    :class="{ tight }">
-    <slot />
-  </component>
+  <div class="section-header-wrapper">
+    <LoadingSkeleton v-if="loading" />
```
Comment (hwkr) [inline packages/api-reference/src/components/Section/SectionHeader.vue:16]: To be honest I don't know if this skeleton actually works...

**Review by hwkr — CHANGES_REQUESTED** [review]
Looks good! I think we probably just want to swap that media query for a container query, also would be good to get @cameronrohani's 👀 on this before merging because he wrote a bunch of that layout logic.

File: packages/api-reference/src/components/Section/SectionHeader.vue (hunk 3 above)
Comment (hanspagel) [reply packages/api-reference/src/components/Section/SectionHeader.vue:16]: I doubt it, too. Haven’t seen it in a while. 😅

Comment (antlio) [reply packages/api-reference/src/components/Section/SectionHeader.vue:16]: I just kept (moved) what we have nothing else, but we could ff and remove it if need

**Review by hanspagel — APPROVED** [review]
LGTM, but I leave this to @hwkr and @cameronrohani

File: packages/api-reference/src/components/Section/SectionHeader.vue (hunk 3 above)
Comment (hwkr) [reply packages/api-reference/src/components/Section/SectionHeader.vue:16]: Yeah sorry that wasn't an action item for you just me noticing it.

**Review by hwkr — APPROVED** [review]
Looks good! Thanks for swapping those queries :)
