### PR TITLE
fix(api-client): add collection.info.version optional

### LINKED ISSUE #3463: allow info.version: null
the api client breaks if the document has `info.version: null`, let's be easy with that, it’s totally okay and actually AFAIK completely irrelevant for the client if this value is `null`. :)

image

```json
{
"openapi": "3.1.0",
"info": {
"title": "Nitro Server Routes",
"version": null
}
}
```

### PR DESCRIPTION
**Pull request by amritk**
fix #3463 
Turns out we already had a default, was just missing optional()

### CODE REVIEW

File: packages/oas-utils/src/entities/spec/spec-objects.ts [hunk 1]
```diff
@@ -57,7 +57,7 @@ export const oasInfoSchema = z.object({
    * REQUIRED. The version of the OpenAPI document (which is distinct from the OpenAPI
    * Specification version or the API implementation version).
    */
-  version: z.string().default('0.0.1'),
+  version: z.string().optional().default('0.0.1'),
```
Comment (hanspagel) [inline packages/oas-utils/src/entities/spec/spec-objects.ts:60]: Not related to this PR, but maybe a great opportunity to clean this up:

Semantic versions start at 0.1.0, not 0.0.1. But I think the default should just be `null`. I don’t see a reason to make up a version number if the users doesn’t add one. Wdyt?

**Review by hanspagel — CHANGES_REQUESTED** [review]

File: packages/oas-utils/src/entities/spec/spec-objects.ts (hunk 1 above)
Comment (amritk) [reply packages/oas-utils/src/entities/spec/spec-objects.ts:60]: I disagree just because the spec says it is required, so one should always exist. The integrations should just pull it from the package.json

File: packages/api-client/package.json [hunk 2]
```diff
@@ -77,11 +77,6 @@
       "types": "./dist/libs/importers/index.d.ts",
       "default": "./dist/libs/importers/index.js"
     },
-    "./libs/event-busses": {
-      "import": "./dist/libs/event-busses/index.js",
-      "types": "./dist/libs/event-busses/index.d.ts",
-      "default": "./dist/libs/event-busses/index.js"
-    },
```
[the remark this answers is not in the document]
Comment (amritk) [reply packages/api-client/package.json:84]: Yea this one is from some other changes, popped up in a few of my prs

File: packages/oas-utils/src/entities/spec/spec-objects.ts (hunk 1 above)
Comment (hanspagel) [reply packages/oas-utils/src/entities/spec/spec-objects.ts:60]: What package.json? 🤔 This is for whatever OpenAPI document the user gives us, right? There’s no package.json involved typically.

Let’s use 1.0 as the default then, though. Feels like a better fallback.

```suggestion
  version: z.string().optional().default('1.0'),
```

**Review by hanspagel — APPROVED** [review]
LET’S GE T   T HIS   INN
