### PR TITLE
fix(openapi-parser): example arrays are transformed to objects

### LINKED ISSUE #4075: Example array is not displayed correctly in the Test request.
### What happens?

in Reference
Screenshot 2567-12-03 at 17 04 37
in Test request
Screenshot 2567-12-03 at 17 06 46

### What did you expect to happen?

Should display the Example array correctly in the API client.

### OpenAPI Document

https://sandbox.scalar.com/p/lK1I9#tag/templates/POST/template

### PR DESCRIPTION
**Pull request by hanspagel**
**Problem**
Currently, in some cases arrays are converted to objects during in the `upgrade` helper.

**Solution**
With this PR arrays will be arrays after the upgrade.

Fixes #4075 #3782.

**Example**

https://sandbox.scalar.com/e/fi5lT

**Before**

Screenshot 2025-01-13 at 15 11 53

**After**

Screenshot 2025-01-13 at 15 12 18

**Checklist**

I’ve gone through the following:

- [x] I’ve added an explanation _why_ this change is needed.
- [x] I’ve added a changeset (`pnpm changeset`).
- [x] I’ve added tests for the regression or new feature.
- [ ] I’ve updated the documentation.

### CODE REVIEW

**Review by antlio — APPROVED** [review]
great

File: packages/openapi-parser/src/utils/traverse.ts [hunk 1]
```diff
@@ -14,12 +14,17 @@ export function traverse(
...
-        if (typeof item === 'object' && item !== null) {
+        if (typeof item === 'object' && !Array.isArray(item) && item !== null) {
           return traverse(item, transform, [...currentPath, index.toString()])
         }
+
         return item
       })
-    } else if (typeof value === 'object' && value !== null) {
+    } else if (
+      typeof value === 'object' &&
```
Comment (amritk) [inline packages/openapi-parser/src/utils/traverse.ts:24]: ah yes of course! they should add this rule into typescript

**Review by amritk — APPROVED** [review]
