### PR TITLE
fix(api-client): handle `onBeforeRequest` hook error

### LINKED ISSUE #7303: `onBeforeRequest` errors make the request loading indefinitely
### What happens?

When an error occurs inside `onBeforeRequest` the user is not notified and the request cannot be cancelled

### Reproduction

<details><summary>Video</summary>
<p>

https://github.com/user-attachments/assets/2f965a9e-e7b6-4e94-83aa-861d3d55dcd4

</p>
</details> 

You can paste the following snippet in `packages/api-reference/index.html` to test this behaviour:

<details><summary>Snippet</summary>
<p>

```html
<!doctype html>
<html>
  <head>
    <title>Scalar API Reference</title>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1" />
  </head>

  <body>
    <div id="app"></div>

    <!-- Our Script -->
    <script
      src="src/standalone.ts"
      type="module"></script>

    <!-- Initialize the Scalar API Reference -->
    <script type="module">
      import { sources } from './test/utils/sources.ts'

      Scalar.createApiReference('#app', {
        sources,
        persistAuth: true,
        // Avoid CORS issues
        proxyUrl: 'https://proxy.scalar.com',
        async onBeforeRequest() {
          await new Promise((_, reject) => {
            setTimeout(() => {
              try {
                foo.bar
              } catch (e) {
                reject(e)
              }
            }, 2000)
          })
        },
      })
    </script>
  </body>
</html>
```

</p>
</details> 

### What did you expect to happen?

A toast appears informing that an error occurred in `onBeforeRequest` and the request is aborted

### OpenAPI Document

N/A

### PR DESCRIPTION
**Pull request by marcalexiei**
**Problem**

- Closes #7303 

**Solution**

Handle errors coming from `onBeforeRequest` hook in `create-request-operation.ts`.
I identified several deprecated functions and variables and replaced them with their updated counterparts.

**Checklist**

I've gone through the following:

- [x] I've added an explanation _why_ this change is needed.
- [x] I've added a changeset (`pnpm changeset`).
- [x] I've added tests for the regression or new feature.
- [x] I've updated the documentation (Not needed).

---

> [!NOTE]
> Gracefully handles `onBeforeRequest` hook failures by aborting and returning a normalized error; updates helpers/imports, tweaks AddressBar icon/handlers, and adds tests.
> 
> - **api-client**
>   - **Error handling**: Wrap `pluginManager.executeHook('onBeforeRequest')` in try/catch in `libs/send-request/create-request-operation.ts`; on error, emit `abort` and return `[Error(ERRORS.ON_BEFORE_REQUEST_FAILED), null]`.
>   - **Errors**: Add `ERRORS.ON_BEFORE_REQUEST_FAILED` in `libs/errors.ts`.
>   - **Helpers/Imports**: Migrate to `@scalar/helpers` (`isDefined`, `httpStatusCodes`, `mergeUrls`); keep proxy utilities from `@scalar/oas-utils/helpers`.
> - **UI**
>   - `components/AddressBar/AddressBar.vue`: Replace generic icon with `ScalarIconPlay`; source `REQUEST_METHODS` from `@scalar/helpers/...`; adjust request status handlers to `return` early and add `status satisfies undefined`.
> - **Tests**
>   - Add test asserting resolution with error tuple when `onBeforeRequest` rejects in `create-request-operation.test.ts`; maintain hooks ordering and response handling assertions.
> - **Changeset**
>   - Patch release for `@scalar/api-client`.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit c0459c4a6c9fb747b199d6faf182db3a0f00deaf. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: packages/api-client/src/libs/send-request/create-request-operation.ts [hunk 1]
```diff
@@ -190,7 +193,13 @@ export const createRequestOperation = ({
       status?.emit('start')
 
       if (pluginManager) {
-        await pluginManager.executeHook('onBeforeRequest', { request: proxiedRequest })
+        try {
+          await pluginManager.executeHook('onBeforeRequest', { request: proxiedRequest })
+        } catch (e) {
+          const _e = new Error(ERRORS.ON_BEFORE_REQUEST_FAILED, { cause: e })
+          status?.emit('abort')
+          return [normalizeError(_e), null]
```
Comment (marcalexiei) [inline packages/api-client/src/libs/send-request/create-request-operation.ts:201]: After reviewing [cursor comment](https://github.com/scalar/scalar/pull/7304#pullrequestreview-3436754768) I opted to create an error using [`cause`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/cause) option.

This is the result: 

Image
