### PR TITLE
fix(themes): remove variables from theme layer and move selection to default theme

### LINKED ISSUE #3388: Theming stopped working in the React wrapper
### What happens?

After switching to the latest version 0.3.104 of @scalar/api-reference-react, themes stopped working. Switching between light and dark mode still works, but the custom background from themes like "kepler" don't apply anymore.

The last version that worked as expected was 0.3.19.

### What did you expect to happen?

I expected to get the same theme styling as per examples and documentation when applying it on the configuration.

### How can we reproduce the issue?

```javascript
'use client';
import React from 'react';
import { ApiReferenceReact } from '@scalar/api-reference-react';
import '@scalar/api-reference-react/style.css'

type Props = {
    spec: Record<string, any>;
};

const Docs = ({ spec }: Props): React.ReactElement => {
    return (
        <ApiReferenceReact
            configuration={{
                spec: {
                    content: spec
                },
                layout: 'modern',
                theme: 'kepler',
                hideDownloadButton: true,
                hideModels: true,
                darkMode: true,
            }}
        />
    );
};

export default Docs;
```

### OpenAPI Document

_No response_

### PR DESCRIPTION
**Pull request by hwkr**
Looks like we were injecting a copy of `variables.css` from `@scalar/themes` into the `scalar-theme` layer, we already import `variables.css` into the `scalar-base` layer as part of `@scalar/themes/style.css`.

It's important it's only in the `scalar-base` layer otherwise there's a risk of the default variables overriding theme variables (which is the issue in #3388). This updates the precedence to be:

1. Any user styles that they add to the page outside of a css layer
2. The theme injected into the `scalar-theme` css layer via [`getThemeStyles()`](https://github.com/scalar/scalar/blob/6279c5977c5067f21c61d4d91d7963f4a4b9a384/packages/themes/src/index.ts#L114) (includes any selection color overrides)
3. The variables & default (base) theme injected into the `scalar-base` css layer by importing [`@scalar/themes/style.css`](https://github.com/scalar/scalar/blob/6279c5977c5067f21c61d4d91d7963f4a4b9a384/packages/themes/src/style.css) (includes the default selection color configuration)

I also moved the base / default css variables for the selections into the default theme because they're more colors than root variables (they should work in either file now though). 

Fixes #3388

## Before

Google Chrome-2024-10-07-13-55-04@2x

## After

Google Chrome-2024-10-07-13-29-32@2x

### CODE REVIEW

File: packages/api-client/src/layouts/App/ApiClientApp.vue [hunk 1]
```diff
@@ -54,19 +54,16 @@ const handleKeyDown = (ev: KeyboardEvent) => handleHotKeyDown(ev, { hotKeys })
 onMounted(() => window.addEventListener('keydown', handleKeyDown))
 onBeforeUnmount(() => window.removeEventListener('keydown', handleKeyDown))
 
-const fontsStyleTag = computed(
+const themeStyleTag = computed(
```
Comment (hwkr) [inline packages/api-client/src/layouts/App/ApiClientApp.vue:57]: Also renamed these to reflect what they're doing

**Review by antlio — APPROVED** [review]
great job!!

**Review by hanspagel — APPROVED** [review]
Great fix, awesome explanation!

**Review by cameronrohani — APPROVED** [review]
