### PR TITLE
fix(api-reference): complex security requirements

### LINKED ISSUE #3359: Missing combined security schema UI
### What happens?

I have a combined security schema defined as follows:
```
security:
 - bearerAuth: [ ]
   apiKeyHeader: [ ]
```
I am using @scalar/api-reference 1.25.25 package
when I try "Test Request" on one of the endpoints with authentication required there is no option for selecting combined Bearer & Subscription Key authentication type.

image

It used to look like this:
image

Is there a way now to select combined schema as the preferred security schema? 
Examples in the api-reference are now misleading because they show only one schema used (here it is --header 'X-Api-Key: YOUR_TOKEN', but I need both api key and bearer token for authentication)
image

### What did you expect to happen?

Having option to select combined security schema which will be reflected in both api-client and api-reference examples

### OpenAPI Document

[Sandbox](https://sandbox.scalar.com/e/LSMHy)

### PR DESCRIPTION
**Pull request by amritk**
Complex security, this was done a few times but kept breaking whenever we refactored or changed something. Have now added tests to ensure this does not happen again!

fixes #3359

currently needs
- [x] integration tests
- [x] switch to array instead of comma

Originally I did it the easy way with much less changes, but it was not quite correct. So I switched from comma separated to using a proper array! Also switched to prop drilling so we can add integration tests :). Now the integration tests are still a little basic as we have a lot of reliance on `useActiveEntities` but I will keep drilling 

**Problem**
Complex auth was broken

**Solution**
We add back in complex auth

**To test**
load up the client and import this spec to test
`https://gist.githubusercontent.com/amritk/f64887015e998bf81ff349d3ace64cd5/raw/4499a362e1f274ef7f2f61e7f572c34dfa67e4db/test.yml`
the key part is
```json
  "security": [
    {
      "bearerAuth": [],
      "apiKeyQuery": []
    },
  ],
```
which has two security schemes in a single requirement

image
@cameronrohani I just stacked em like this, feel like it makes sense?

image

**Checklist**

I’ve gone through the following:

- [x] I’ve added an explanation _why_ this change is needed.
- [x] I’ve added a changeset (`pnpm changeset`).
- [x] I’ve added tests for the regression or new feature.
- [ ] I’ve updated the documentation.

See the [contributing guide](https://github.com/scalar/scalar/blob/main/CONTRIBUTING.md) for more information.

### CODE REVIEW

**Comment by antlio** [comment]
great work! i'm wondering if we could save some duplicated infos and space by playing with the label:

| before | after |
| -------|------|
| image | image |
| current PR state | proposal to use label to differentiate auth |

**Comment by amritk** [comment]
> great work! i'm wondering if we could save some duplicated infos and space by playing with the label:
> 
> before	after
> image	image
> current PR state	proposal to use label to differentiate auth

yea that works, but we can fast follow, lets get this one in first!

File: packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestAuthTab.vue [hunk 1]
```diff
@@ -165,9 +179,12 @@ const updateScheme = <U extends string, P extends Path<SecurityScheme>>(
         :key="key">
         <OAuth2
           v-if="activeFlow === key || (ind === 0 && !activeFlow)"
+          :collection="collection"
           :flow="flow!"
           :layout="layout"
-          :scheme="scheme" />
+          :scheme="scheme"
```
Comment (amritk) [inline packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestAuthTab.vue:185]: Prop drillin

Comment (antlio) [reply packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestAuthTab.vue:185]: 🚨

File: packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestAuth.vue [hunk 2]
```diff
@@ -86,57 +91,53 @@ const authIndicator = computed(() => {
...
-
+const editSelectedSchemeUids = (uids: SelectedSecuritySchemeUids) => {
   // Set as selected on the collection for the modal
-  if (layout === 'modal' || layout === 'reference') {
-    collectionMutators.edit(
-      activeCollection.value.uid,
-      'selectedSecuritySchemeUids',
-      uids,
-    )
+  if (hookLayout === 'modal' || propLayout === 'reference') {
```
[the remark this answers is not in the document]
Comment (antlio) [reply packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestAuth.vue:135]: yes! i should give a deeper thought about how to make this easier to handle

**Review by marclave — APPROVED** [review]
unreal work @amritk 🫵🐐
