### PR TITLE
fix(#1138): docusaurus plugin not loading

### LINKED ISSUE #1138: Docusarus bug when not using Typescript
### What happens?

When running my sit, after npm start. I get the following error:

```

Module not found: Error: Can't resolve '/Users/tatiana/Documents/my-website/node_modules/@scalar/docusaurus/dist/ScalarDocusaurus' in '/Users/tatiana/Documents/my-website/.docusaurus'

--------------------------

Module not found: Error: Can't resolve '/Users/tatiana/Documents/my-website/node_modules/@scalar/docusaurus/dist/ScalarDocusaurus' in '/Users/tatiana/Documents/my-website/.docusaurus'
client (webpack 5.90.3) compiled with 2 errors
```

### What did you expect to happen?

For the site to start and for the plugin to load

### How can we reproduce the issue?

I am not using typescript. In a `docusaurus.config.js` add the following, then npm start.

```
  plugins: [
    [
      '@scalar/docusaurus',
      {
        label: 'Scalar',
        route: '/scalar',
        configuration: {
          spec: {
            url: 'https://petstore3.swagger.io/api/v3/openapi.json',
          },
        },
      }
    ],
  ],
  ```

### Swagger/OpenAPI Example

https://petstore3.swagger.io/api/v3/openapi.json

### PR DESCRIPTION
**Pull request by amritk**
This fixes #1138, some testing code leftover.

I just found another issue with mobile, will fix in this PR.

### CODE REVIEW

**Review by marclave — APPROVED** [review]
🖖

File: packages/swagger-parser/src/helpers/fetch-spec.ts [hunk 1]
```diff
@@ -17,30 +17,42 @@ function jsonOrYaml(value: string) {
...
-    const proxyWarning = proxy
-      ? ''
-      : 'Trying to fetch the spec file without a proxy. The CORS headers have to be set properly, otherwise the request will fail.'
-    console.error(
-      `[fetchSpecFromUrl] Failed to fetch the spec at ${url}. ${proxyWarning}`,
-    )
-  }
+    const payload = await response.json()
 
-  const payload = await response.text()
```
Comment (geoffgscott) [inline packages/swagger-parser/src/helpers/fetch-spec.ts:42]:
```
const payload = proxy ? (await response.json).data : await response.text()
```
