### PR TITLE
fix: unused empty tags break sidebar, fix #1535

### LINKED ISSUE #1535: Extra tags that are not being used cause routes to not being shown in sidebar
### What happens?

Sidebar is empty.
Happens since version 1.20.27

### What did you expect to happen?

Sidebar to show routes

### How can we reproduce the issue?

1. https://sandbox.scalar.com/e/OawyV
2. See empty sidebar
3. Delete lines 9-12
4. Sidebar shows routes

### Swagger/OpenAPI Example

https://sandbox.scalar.com/e/OawyV

### PR DESCRIPTION
**Pull request by hanspagel**
Currently, the sidebar disappears if you have unused, empty tags. See #1535 for more context.

This is because we’ve had a check in place, that was wrong. It just skipped the output if the first tag doesn’t have an operation attached.

This PR fixes it. :)

### CODE REVIEW

File: packages/api-reference/src/hooks/useSidebar.ts [hunk 1]
```diff
@@ -91,35 +91,41 @@ const items = computed(() => {
...
-      ? parsedSpec.value?.tags?.map((tag: Tag) => {
-          return {
-            id: getTagId(tag),
-            title: tag.name.toUpperCase(),
-            show: true,
-            children: tag.operations?.map((operation: TransformedOperation) => {
-              const id = getOperationId(operation, tag)
-              const title = operation.name ?? operation.path
-              titlesById[id] = title
+  console.log(moreThanOneDefaultTag(parsedSpec.value?.tags))
```
Comment (marclave) [inline packages/api-reference/src/hooks/useSidebar.ts:94]: can remove this stray log ✨

File: packages/api-reference/src/hooks/useSidebar.ts [hunk 2]
```diff
@@ -91,35 +91,41 @@ const items = computed(() => {
...
-                select: () => {
-                  if (state.showApiClient) {
-                    openClientFor(operation, globalSecurity)
+  const operationEntries: SidebarEntry[] | undefined =
+    firstTag && moreThanOneDefaultTag(parsedSpec.value?.tags)
+      ? parsedSpec.value?.tags
+          // Filter out tags without operations
+          ?.filter((tag: Tag) => tag.operations?.length > 0)
+          .map((tag: Tag) => {
+            console.log('loop through tag', tag)
```
Comment (marclave) [inline packages/api-reference/src/hooks/useSidebar.ts:102]: and this stray log 🤯

**Comment by hanspagel** [comment]
Oops, embarrassing! I removed the stray logs. 🙈
