### PR TITLE
fix(api-client): content-type request 

### LINKED ISSUE #4562: Custom content type open api support
### What happens?

Got a small issue i've ran into today -- I've got a Json PATCH endpoint that requires a Content-Type header of 'application/json-patch+json' (.NET backend) to function correctly. I've got a custom document transformer that sets the expected content-type of the body correctly, and this is reflected in the documentation (see attached) but when hitting 'Test Request' it is just defaulted to application/json

Is there anyway to override this default Content-Type header for PATCH requests -- maybe on the Scalar side of things?

Image

Image

_originally posted by Ceece [in discord](https://discord.com/channels/1135330207960678410/1331254815866748979)_

### PR DESCRIPTION
**Pull request by antlio**
**Problem**
currently when using a custom content type it is not retrieved at the client modal level and also override the example once back to the reference.

**Solution**
this pr sets the request content-type if present and fixes #4562.

| before | after |
| -------|------|
| image | image |
| content-type is using json | content-type is using custom | 

**Checklist**

I’ve gone through the following:

- [x] I’ve added an explanation _why_ this change is needed.
- [x] I’ve added a changeset (`pnpm changeset`).
- [ ] I’ve added tests for the regression or new feature.
- [ ] I’ve updated the documentation.

See the [contributing guide](https://github.com/scalar/scalar/blob/main/CONTRIBUTING.md) for more information.

### CODE REVIEW

File: packages/api-client/src/views/Request/RequestSection/RequestBody.vue [hunk 1]
```diff
@@ -73,7 +73,12 @@ const activeExampleContentType = computed(() => {
     return activeExample.value.body.raw.encoding
   }
 
-  return 'none'
+  // Set content type from request if present
+  const contentType = Object.keys(
+    activeRequest.value?.requestBody?.content || {},
```
Comment (amritk) [inline packages/api-client/src/views/Request/RequestSection/RequestBody.vue:78]: should we start storing content type on the example? Where did we land on example per content type again?

Comment (amritk) [reply packages/api-client/src/views/Request/RequestSection/RequestBody.vue:78]: lets chat rq

Comment (antlio) [reply packages/api-client/src/views/Request/RequestSection/RequestBody.vue:78]: its more of a quick fix to be refactored once the above gets in - #4485

Comment (amritk) [reply packages/api-client/src/views/Request/RequestSection/RequestBody.vue:78]: Ok send it

**Review by amritk — APPROVED** [review]
