### PR TITLE
fix(api-client): resolve oauth URLs for relative servers

### LINKED ISSUE #7524: OAuth2 password flow: relative tokenUrl not resolved against server URL
## Description

When using OAuth2 password flow with a relative `tokenUrl` in the OpenAPI schema, Scalar does not resolve it against the configured server URL. Instead, it calls the relative path directly, resulting in 404 errors.

## Steps to Reproduce

1. Create a FastAPI subapp mounted at `/partners`
2. Define OAuth2 with relative tokenUrl:
   ```python
   oauth2_scheme = OAuth2PasswordBearer(tokenUrl="auth/token")
   ```
3. The generated OpenAPI schema correctly includes:
   ```json
   {
     "servers": [{"url": "/partners"}],
     "components": {
       "securitySchemes": {
         "OAuth2": {
           "type": "oauth2",
           "flows": {
             "password": {
               "tokenUrl": "auth/token",
               "scopes": {}
             }
           }
         }
       }
     }
   }
   ```
4. Open Scalar (`/partners/explorer`) and attempt OAuth2 "Username & Password" authentication

## Expected Behavior

Per the OpenAPI specification, relative URLs should be resolved against the server URL.

- Server: `/partners`
- tokenUrl: `auth/token`
- **Expected resolved URL:** `/partners/auth/token`

## Actual Behavior

Scalar calls `/auth/token` directly without resolving against the server URL, resulting in a 404 error.

## Related Issues

- #3700 - "authorize button doesn't work with relative URLs" - Fixed in #3714, but only for `redirectURI`
- #3714 - PR that prefixes relative `redirectURI` with activeServer - **same fix needed for `tokenUrl`**
- #1987 - "OAuth: Use authorizationUrl, tokenUrl and redirectUri properly"

## Suggested Fix

Apply the same logic from PR #3714 to `tokenUrl` (and `authorizationUrl`): if the URL is relative (starts with no scheme and no `/`), prefix it with the active server URL.

## Environment

- scalar-fastapi: 1.4.4
- @scalar/api-reference: latest (via CDN)
- FastAPI: 0.115.x
- Browser: Chrome/Safari

### PR DESCRIPTION
**Pull request by galah92**
## Summary
- resolve OAuth2 authorization/token URLs against relative server URLs
- cover relative server + relative tokenUrl in oauth tests
- add changeset for api-client/api-reference

## Testing
- not run (not requested)

Closes #7524

### CODE REVIEW

**Comment by hanspagel** [comment]
thanks for submitting the PR!

I will leave this to @amritk and @DemonHa

File: packages/api-client/src/views/Request/libs/oauth2.ts [hunk 1]
```diff
@@ -14,6 +15,20 @@ type PKCEState = {
   codeChallengeMethod: string
 }
 
+const getActiveServerBase = (activeServer?: Server) => {
```
Comment (amritk) [inline packages/api-client/src/views/Request/libs/oauth2.ts:18]: these old files will be deleted soon! Hopefully end of this week/next week
