### PR TITLE
fix(api-client): UI breaking when response body too big

### LINKED ISSUE #4365: UI broken when body response is too big
### What happens?

Hi,

When receiving a response in the body that is too big, the layout completely breaks, and overflows to the right. Parent containers have overflow hidden so we can't see it, and even if we tab to it, the scroll causes massive re-renders and it's basically unusable.

I think there is a cap to it. I tried with a response that was 220K characters, it displayed fine, but 252K and 290K character responses it broke.
I wonder if there is a limit of characters? Maybe 250K

### What did you expect to happen?

Display the full response.

### OpenAPI Document

_No response_

### PR DESCRIPTION
**Pull request by RemcoGoy**
**Problem**
Currently, when receiving a response body above the virtualization threshold, the UI breaks, leaving the user unable to view the actual response body.

**Solution**
With this PR, I've updated the CSS from the component to fix this issue.

**Linked Issue**
closes #4365 

**Changes**

1. Added `overflow-x-auto` on the `ResponseBodyVirtual` component to fix the actual issue
2. Removed `mx-1` on the subcomponents to remove gap around containers

**Checklist**

I’ve gone through the following:

- [x] I’ve added an explanation _why_ this change is needed.
- [x] I’ve added a changeset (`pnpm changeset`).
- [ ] I’ve added tests for the regression or new feature.
- [ ] I’ve updated the documentation.

See the [contributing guide](https://github.com/scalar/scalar/blob/main/CONTRIBUTING.md) for more information.

---

Feel free to let me know if I can improve anything.

### CODE REVIEW

File: packages/api-client/src/views/Request/ResponseSection/ResponseBodyVirtual.vue [hunk 1]
```diff
@@ -12,14 +12,15 @@ const textContent = computed(() => formatJsonOrYamlString(props.content))
 </script>
 
 <template>
-  <ViewLayoutCollapse class="!max-h-[calc(100%-32px)] response-body-virtual">
+  <ViewLayoutCollapse
+    class="a!max-h-[calc(100%-32px)] overflow-x-auto response-body-virtual">
```
Comment (amritk) [inline packages/api-client/src/views/Request/ResponseSection/ResponseBodyVirtual.vue:16]:
```suggestion
    class="!max-h-[calc(100%-32px)] overflow-x-auto response-body-virtual">
```

typo? 😄

**Review by hwkr — COMMENTED** [review]
Looks good to me! Thanks for the contribution @RemcoGoy!

**Comment by amritk** [comment]
Thanks for the wicked fix @RemcoGoy, I added a couple changes:
- removed the `hljs` class which was causing performance issues
- removed position absolute which wasn't required
- copied the relevant styles out from `hljs`

can we get a style check @cameronrohani @marclave

**Review by amritk — APPROVED** [review]
