### PR TITLE
fix(api-reference): allof items merge objects

### LINKED ISSUE #2137: Wrong example response for array with items that use allOf
### What happens?

The example response renders wrong objects in the array

### What did you expect to happen?

The example response is correct

### How can we reproduce the issue?

Use the provided example or clone this test repo https://github.com/macno/scalar-api-allOf-bug

### OpenAPI Document

https://sandbox.scalar.com/e/ZydCR

### PR DESCRIPTION
**Pull request by antlio**
this pr is a proposal to fix #2137 in order to merge objects in response example for allof items.

image

### CODE REVIEW

File: packages/api-reference/src/components/Content/Operation/PathResponses/ExampleResponse.vue [hunk 1]
```diff
@@ -97,6 +85,31 @@ const mergeAllObjects = (items: Record<any, any>[]): any => {
...
+      v-if="response?.schema['items']?.['allOf']"
+      :content="
+        mergeAllObjects(
+          response?.schema['items']['allOf'].map((schema: any) =>
+            getExampleFromSchema(schema, {
+              emptyString: '…',
+              mode: 'read',
+            }),
+          ),
+        )
```
Comment (hanspagel) [inline packages/api-reference/src/components/Content/Operation/PathResponses/ExampleResponse.vue:98]: does mergeAllObjects with ciruclar references? 🤔

**Review by hanspagel — CHANGES_REQUESTED** [review]
left a comment, don’t know the answer, but besides that: looks good to me!

File: packages/api-reference/src/components/Content/Operation/PathResponses/ExampleResponse.vue (hunk 1 above)
Comment (marclave) [reply packages/api-reference/src/components/Content/Operation/PathResponses/ExampleResponse.vue:98]: @antlio would you be able to test w circular refs? : )

Comment (hanspagel) [reply packages/api-reference/src/components/Content/Operation/PathResponses/ExampleResponse.vue:98]: I added a test, works fine!

**Review by hanspagel — APPROVED** [review]
