### PR TITLE
fix(api-reference): title and higher level discriminator support

### LINKED ISSUE #5447: anyOf in array in nested object does not show type definitions
### What happens?

I have an array where mixed items are allowed. When this array is in an object, then the type is not showed.

### What did you expect to happen?

The type should be showed.

### OpenAPI Document

https://sandbox.scalar.com/e/y6zb3

### LINKED ISSUE #5488: api-reference does not support `anyOf[number].title`
### What happens?

Scalar takes the name of the first key in the object

Image

### What did you expect to happen?

In Redocly, as an example where it works, value of "anyOf[number].title" changes the tab's label; on the screenshot where you see: Any of and two  "title" "title" tabs

### OpenAPI Document

https://sandbox.scalar.com/e/LaRjM

### PR DESCRIPTION
**Pull request by antlio**
**Problem**

currently when any of discriminator includes a title with value, it is not retrieved within the tab.

**Solution**

this pr adds:
- support of title value that fixes #5488 
- update schema discriminator logic that fixes #5447
- dropdown for long discriminator content usage follow up #5429
- style enhancement finalizing #795

`title`
| before | after |
| -------|------|
| image | image |

`deeper level`
| before | after |
| -------|------|
| image | image |

`long content support`
| before | after |
| -------|------|
| image | image |

**Checklist**

I’ve gone through the following:

- [x] I’ve added an explanation _why_ this change is needed.
- [x] I’ve added a changeset (`pnpm changeset`).
- [x] I’ve added tests for the regression or new feature.
- [ ] I’ve updated the documentation.

### CODE REVIEW

File: packages/api-reference/src/components/Content/Schema/SchemaProperty.vue [hunk 1]
```diff
@@ -314,7 +314,7 @@ const displayPropertyHeading = (
           typeof optimizedValue.items === 'object' &&
           discriminator in optimizedValue.items &&
           Array.isArray(optimizedValue.items[discriminator]) &&
-          level < 3
+          level < 5
```
Comment (antlio) [inline packages/api-reference/src/components/Content/Schema/SchemaProperty.vue:317]: any cons in passing directly optimizedValue here?

Comment (hanspagel) [reply packages/api-reference/src/components/Content/Schema/SchemaProperty.vue:317]: Idk, give it a try!

**Review by hanspagel — APPROVED** [review]
great improvement
