### PR TITLE
fix: doesn’t show webhooks when x-tagGroups are used, fix #2172

### LINKED ISSUE #2172: OpenAPI 3.1 webhooks are not displayed if x-tagGroups are used
### What happens?

Given an OpenAPI 3.1 file that contains both `x-tagGroups` (implemented in #1174) and `webhooks`, the webhooks are not displayed in the Scalar sidebar. This happens even if the webhooks use `tags` listed in `x-tagGroups`.

Without `x-tagGroups`:
Screenshot 2024-06-19 at 16 51 09

With `x-tagGroups`:
Screenshot 2024-06-19 at 16 52 29

### What did you expect to happen?

The sidebar should still have the "Webhooks" category/group with a list of defined webhooks.

I think webhooks should always be displayed in `x-tagGroups` scenarios even if the webhooks themselves don't have `tags`.

### How can we reproduce the issue?

1. Go to https://sandbox.scalar.com.
2. Paste the text from
https://gist.githubusercontent.com/hkosova/e1b6ce4d72a3ec722ad4802d77f7e3e4/raw/fa790231d345af0c4779b01f6e81a7937a229030/webhooks-tag-groups.json
into the editor.
3. Examine the sidebar in the preview.

### OpenAPI Document

https://gist.githubusercontent.com/hkosova/e1b6ce4d72a3ec722ad4802d77f7e3e4/raw/fa790231d345af0c4779b01f6e81a7937a229030/webhooks-tag-groups.json

### PR DESCRIPTION
**Pull request by hanspagel**
If x-tagGroups are used, the webhooks don’t show up anymore. See #2172 for more context.

This PR adds test for `useSidebar` (finally!) and fixes the bug.

**Example Definition**
https://gist.githubusercontent.com/hkosova/e1b6ce4d72a3ec722ad4802d77f7e3e4/raw/fa790231d345af0c4779b01f6e81a7937a229030/webhooks-tag-groups.json

### CODE REVIEW

File: packages/api-reference/src/hooks/useSidebar.ts [hunk 1]
```diff
@@ -256,12 +228,49 @@ const items = computed(() => {
...
+    : undefined
+
   return {
     entries: [
       ...headingEntries,
       ...(groupOperations ?? operationEntries ?? []),
-      ...(groupOperations ? [] : webhookEntries),
-      ...(groupOperations ? [] : modelEntries),
+      ...webhookEntries,
+      ...modelEntries,
```
Comment (hanspagel) [inline packages/api-reference/src/hooks/useSidebar.ts:273]: This made the webhooks disappear.

**Review by marclave — APPROVED** [review]
nice work @hanspagel ✨
