### PR TITLE
fix(api-client): all request bodies are sent as form data, fix #2511

### LINKED ISSUE #2511: JSON Request Body Sent as FormData
### What happens?

When testing the request, selecting the JSON type for the request body results in the data being sent as FormData instead of JSON. This leads to unexpected behavior in the API and makes it difficult to test JSON endpoints properly.

Version: 
"@scalar/fastify-api-reference": "^1.24.46"

### What did you expect to happen?

The request should be sent with the body formatted as JSON.

### How can we reproduce the issue?

Steps to Reproduce:

1. Navigate to the request testing interface.
2. Select the request type as JSON.
3. Enter a JSON object in the request body.
4. Send the request.

### OpenAPI Document

`
    "/auth/login": {
      "post": {
        "operationId": "auth_login",
        "summary": "Login",
        "tags": ["auth"],
        "security": [{ "noAuth": [] }],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": { "type": "string", "format": "email", "description": "The email address of the user." },
                  "password": { "type": "string", "description": "The password of the user in plain-text." }
                },
                "required": ["email", "password"]
              }
            }
          }
        },`

### PR DESCRIPTION
**Pull request by marclave**
**Problem**
Currently we don't save the raw encoding value and if you change we dont properly set the content-type

**Explanation**
This happens because we dont handle it

**Solution**
With this PR we save both the raw encoding value and set the Content-Type header depending on the content type

https://github.com/user-attachments/assets/771c273a-e29c-496d-9a79-ba9e9bf2a000

### CODE REVIEW

File: packages/api-client/src/views/Request/RequestSection/RequestBody.vue [hunk 1]
```diff
@@ -181,21 +181,52 @@ const updateRequestBody = (content: string) => {
...
+  } else if (type !== 'none') {
     bodyType = 'raw'
+    const mappedType = type === 'other' ? 'html' : type
+    contentTypeHeader = `application/${mappedType}`
+    requestExampleMutators.edit(
+      activeExample.value.uid,
+      'body.raw.encoding',
+      mappedType,
+    )
   }
```
Comment (geoffgscott) [inline packages/api-client/src/views/Request/RequestSection/RequestBody.vue:202]: This logic should really be made functional. Rather than a load of if/else statements and a lot of lets a function that takes the type and just returns `{ bodyType, contentTypeHeader }` would be clearer (and more testable)

File: packages/api-client/src/views/Request/RequestSection/RequestBody.vue [hunk 2]
```diff
@@ -181,21 +181,52 @@ const updateRequestBody = (content: string) => {
...
   )
+
+  if (contentTypeHeader) {
+    // now lets handle the header
+    const headersWithoutContentType = unref(
+      activeExample.value,
+    ).parameters.headers.filter(
+      (header) => header.key.toLowerCase() !== 'Content-Type'.toLowerCase(),
+    )
+    console.log('headersWithoutContentType', headersWithoutContentType)
```
Comment (geoffgscott) [inline packages/api-client/src/views/Request/RequestSection/RequestBody.vue:217]: Stray log

File: packages/api-client/src/views/Request/RequestSection/RequestBody.vue [hunk 3]
```diff
@@ -276,16 +307,16 @@ const selectedContentType = computed({
...
+  if (activeExample.value.body.activeBody === 'formData') {
+    if (
+      activeExample.value.body.formData &&
+      activeExample.value.body.formData.value.length > 0
+    ) {
+      return 'multipartForm'
+    }
+  } else if (activeExample.value.body.activeBody === 'raw') {
     return activeExample.value.body.raw.encoding
+  }
```
Comment (geoffgscott) [inline packages/api-client/src/views/Request/RequestSection/RequestBody.vue:319]: The wrapper `if` is not needed here
```suggestion
  if (
    activeExample.value.body.activeBody === 'formData' &&
    activeExample.value.body.formData &&
    activeExample.value.body.formData.value.length > 0
  )
    return 'multipartForm'

  if (activeExample.value.body.activeBody === 'raw')
    return activeExample.value.body.raw.encoding
```

**Review by geoffgscott — COMMENTED** [review]
Some style changes recommended

**Comment by marclave** [comment]
OMG the weird syncing bug was related to https://github.com/scalar/scalar/pull/2569

🕺 

it works perfectly now
