### PR TITLE
fix(api-client): request params tooltip runtime error

### LINKED ISSUE #4334: Api client throws error if there is no GET method in the OpenAPI spec.
### What happens?

`createApiClientApp` throw error when there is no GET method in the paths.

### What did you expect to happen?

It should work without error. For example it causes gitbook to crash.

https://github.com/user-attachments/assets/0bcf99c9-98bc-413a-b43e-103f276dd4b4

Ekran Resmi 2024-12-23 08 08 00

### OpenAPI Document

[openapi.json](https://petstore3.swagger.io/api/v3/openapi.json)

### PR DESCRIPTION
**Pull request by antlio**
**Problem**
currently empty api client usage through reference is throwing the following error:
image

**Solution**
this pr fixes #4334 as a follow of #4341 and makes sure to only have the clear action available in parameter presence.

tested using api client react playground as highlighted by @marclave.

**Checklist**

I’ve gone through the following:

- [x] I’ve added an explanation _why_ this change is needed.
- [x] I’ve added a changeset (`pnpm changeset`).

### CODE REVIEW

File: packages/api-client/src/views/Request/RequestSection/RequestParams.vue [hunk 1]
```diff
@@ -164,7 +164,8 @@ watch(
       <div
         class="text-c-2 flex whitespace-nowrap opacity-0 group-hover/params:opacity-100 has-[:focus-visible]:opacity-100 request-meta-buttons">
         <!-- TODO fix this DOC-2740 -->
```
Comment (hanspagel) [inline packages/api-client/src/views/Request/RequestSection/RequestParams.vue:166]:
```suggestion
```

**Review by amritk — APPROVED** [review]
Code looks good! @marclave can test the case where it was happening

**Review by marclave — APPROVED** [review]
