### PR TITLE
fix(api-client): mime type transformation issue

### LINKED ISSUE #4525: application/vnd.api+json not rendered as json and is instead detected as a binary file
### What happens?

the mime, `application/vnd.api+json` is rendered like: 

Image

### What did you expect to happen?

https://jsonapi.org/ is json-compatible, so the json-renderer can be used.

_or_ a way to customize how mimes are rendered would be cool.

### OpenAPI Document

➜ Editor:        https://sandbox.scalar.com/e/L5WAS

### PR DESCRIPTION
**Pull request by marclave**
**Problem**
Currently we convert everything to a `json` type and not respecting the proper mime type definition 

**Solution**
With this PR it respects the mime type definition if available ans fixes #4525 

**Checklist**

I’ve gone through the following:

- [x] I’ve added an explanation _why_ this change is needed.
- [x] I’ve added a changeset (`pnpm changeset`).
- [x] I’ve added tests for the regression or new feature.
- [ ] I’ve updated the documentation.

See the [contributing guide](https://github.com/scalar/scalar/blob/main/CONTRIBUTING.md) for more information.

### CODE REVIEW

File: packages/api-client/src/views/Request/RequestSection/RequestBody.vue [hunk 1]
```diff
@@ -68,6 +68,7 @@ const contentTypeOptions = (
 /** Match the activeBody to the contentTypeOptions */
 const activeExampleContentType = computed(() => {
   const { activeBody, formData, raw } = example.body
+  if (raw?.mimeType) return raw.mimeType
```
Comment (marclave) [inline packages/api-client/src/views/Request/RequestSection/RequestBody.vue:71]: @amritk not sure on the best way to do this tbh

File: packages/oas-utils/src/spec-getters/getRequestBodyFromOperation.ts [hunk 2]
```diff
@@ -29,15 +29,15 @@ function getParamsFromObject(
     return [{ name: newKey, value }]
   })
 }
-// Define all supported mime types
-const mimeTypes = [
+// Define preferred standard mime types (order indicates preference)
+const standardMimeTypes: ContentType[] = [
```
Comment (marclave) [inline packages/oas-utils/src/spec-getters/getRequestBodyFromOperation.ts:33]: should we be using this legacy type?

File: packages/oas-utils/src/spec-getters/getRequestBodyFromOperation.ts [hunk 3]
```diff
@@ -47,33 +47,38 @@ export function getRequestBodyFromOperation(
...
-   *
-   * TODO: This is very fragile. There needs to be significantly more support for
-   * vendor specific content types (like application/vnd.github+json)
-   */
-  const mimeType =
-    mimeTypes.find(
-      (currentMimeType: ContentType) => !!content?.[currentMimeType],
-    ) ?? 'application/json'
+  // First try to find a standard mime type
+  let mimeType = standardMimeTypes.find(
```
Comment (marclave) [inline packages/oas-utils/src/spec-getters/getRequestBodyFromOperation.ts:61]: i know we dont like `let`s but yeah not sure on a better way to handle this

**Review by marclave — COMMENTED** [review]
some comments

File: packages/oas-utils/src/entities/spec/request-examples.ts [hunk 4]
```diff
@@ -149,6 +150,7 @@ export const exampleRequestBodySchema = z.object({
     .object({
       encoding: z.enum(exampleRequestBodyEncoding),
       value: z.string().default(''),
+      mimeType: z.string().optional(),
```
Comment (marclave) [inline packages/oas-utils/src/entities/spec/request-examples.ts:153]: we should probably make a schema off `contenttype` eh @amritk ?

File: packages/oas-utils/src/spec-getters/getRequestBodyFromOperation.ts [hunk 5]
```diff
@@ -47,33 +47,38 @@ export function getRequestBodyFromOperation(
...
   text?: string
   params?: {
     name: string
     value?: string
   }[]
 } | null {
-  // Get the content object from the operation
   const originalContent = operation.information?.requestBody?.content
-  const content = normalizeMimeTypeObject(originalContent)
+  const content = originalContent
```
Comment (antlio) [inline packages/oas-utils/src/spec-getters/getRequestBodyFromOperation.ts:58]: should we keep normalizing this and keep ignoring charset?

Comment (antlio) [reply packages/oas-utils/src/spec-getters/getRequestBodyFromOperation.ts]: i updated the function accordingly + added tests

File: packages/oas-utils/src/entities/spec/request-examples.ts [hunk 6]
```diff
@@ -51,7 +52,7 @@ export const requestExampleParametersSchema = z
       data.nullable = true
     }
 
-    // Hey, if it’s just one value and 'null', we can make it a string and ditch the 'null'.
+    // Hey, if it's just one value and 'null', we can make it a string and ditch the 'null'.
```
Comment (hanspagel) [inline packages/oas-utils/src/entities/spec/request-examples.ts:55]:
```suggestion
    // Hey, if it’s just one value and 'null', we can make it a string and ditch the 'null'.
```

**Comment by hanspagel** [comment]
Great work, this needs @amritk’s review

**Comment by ZeroMD** [comment]
From what I saw this also fixes the same issue with Fhir Json that have this mime-type: `application/fhir+json`
https://build.fhir.org/json.html

File: packages/oas-utils/src/entities/spec/request-examples.ts (hunk 4 above)
Comment (amritk) [reply packages/oas-utils/src/entities/spec/request-examples.ts:152]: what kind of schema you thinking? because there's way too many to add an enum

**Review by amritk — CHANGES_REQUESTED** [review]
I'm getting some errors on this one
image

To replicate:
- clear local storage
- import galaxy
- click on create a planet

**Comment by marclave** [comment]
> I'm getting some errors on this one image
> 
> To replicate:
> 
> * clear local storage
> * import galaxy
> * click on create a planet

yeah haha this PR slowly become bigger than what i did, so might take me some time to understand whats going on ✨

**Comment by marclave** [comment]
moving to draft in the meantime

**Comment by amritk** [comment]
hold on maybe im just cooked

**Comment by antlio** [comment]
@amritk let me know if you still have those! PR doesn't do much more that initially as the test were not passing i added the vendor support within the normalize function

**Review by hanspagel — APPROVED** [review]
LGTM, but would be great to have @amritk review this before merging

**Review by amritk — APPROVED** [review]
No more errors
