### PR TITLE
fix(api-reference): display array item const

### LINKED ISSUE #5648: Type array with const value is empty
### What happens?

When I have a type of `array` with `items` of type `const`, then the items do not appear in the `property-heading`.

### What did you expect to happen?

I would expect the array to be shown as `const`.

### OpenAPI Document

https://sandbox.scalar.com/e/u3-yc

### PR DESCRIPTION
**Pull request by antlio**
**Problem**

currently setting a const within an array is not getting displayed in the api reference.

**Solution**

this pr updates the property heading support of const to get it displayed and fixes #5648.

| before | after |
| -------|------|
| image | image |

**Checklist**

I’ve gone through the following:

- [x] I’ve added an explanation _why_ this change is needed.
- [x] I’ve added a changeset (`pnpm changeset`).
- [x] I’ve added tests for the regression or new feature.
- [ ] I’ve updated the documentation.

### CODE REVIEW

File: packages/api-reference/src/components/Content/Schema/SchemaPropertyHeading.vue [hunk 1]
```diff
@@ -81,6 +82,31 @@ const getModelNameFromSchema = (schema: OpenAPI.Document): string | null => {
...
+
+    if (value.items.enum?.length === 1) {
+      return value.items.enum[0]
+    }
+  }
+  return null
+})
+
+/** Check if the schema has a const value */
+const hasConstValue = computed(() => constValue.value !== null)
```
Comment (amritk) [inline packages/api-reference/src/components/Content/Schema/SchemaPropertyHeading.vue:109]:
```suggestion
```
This will be true for undefined! Use the trick that you taught me. I would just check it in the template
```
v-if="isDefined(constValue)"
```

**Review by amritk — COMMENTED** [review]
That was quick!

**Review by marclave — APPROVED** [review]
happy to merge once @amritk 's comment on undefined is implemented

**Review by hanspagel — APPROVED** [review]
happy to merge once @amritk 's comment on undefined is implemented
