### PR TITLE
fix(openapi-parser): ensure upgrader doesn't lose schema properties

### LINKED ISSUE #6537: Upgrader removes schema properties
### What happens?

When using the upgrader

```json
{
  "type": "object",
  "properties": {
    "file": {
      "type": "string",
      "description": "Some fun things",
      "format": "binary"
    }
  }
}
```

becomes 
```json
{
  "type": "object",
  "properties": {
    "file": {
      "type": "string",
      "contentMediaType": "application/octet-stream"
    }
  }
}
```

### What did you expect to happen?

we are removing the old schema properties, we should add a `...schema` spread to all of those returns

https://github.com/scalar/scalar/blob/main/packages/openapi-parser/src/utils/upgrade-from-three-to-three-one.ts

### OpenAPI Document

_No response_

### PR DESCRIPTION
**Pull request by amritk**
**Problem**

closes #6537

Currently, the upgrader will remove all of the old schema properties.

**Solution**

With this PR we only remove format and keep the rest.

**Checklist**

I've gone through the following:

- [x] I've added an explanation _why_ this change is needed.
- [x] I've added a changeset (`pnpm changeset`).
- [x] I've added tests for the regression or new feature.
- [ ] I've updated the documentation.

### CODE REVIEW

File: packages/openapi-parser/src/utils/upgrade-from-three-to-three-one.ts [hunk 1]
```diff
@@ -121,16 +121,21 @@ const applyChangesToDocument = (schema: UnknownObject, path: string[]) => {
     return {}
   }
 
+  // 6. Handle older formats
+  const { format: _, ...rest } = schema
```
Comment (geoffgscott) [inline packages/openapi-parser/src/utils/upgrade-from-three-to-three-one.ts:125]: Is this actually valid though? Are old formats able to be used 1:1? If we do proceed we should probably put a specific JSON schema version locally or at the top of the document.

Comment (amritk) [reply packages/openapi-parser/src/utils/upgrade-from-three-to-three-one.ts:125]: All this does is keep the old properties instead of deleting them. Like description

**Review by geoffgscott — APPROVED** [review]
