### PR TITLE
fix(api-reference): allow scrolling to collapsed sections via hash

### LINKED ISSUE #2603: Internal markdown links don't work if the section is collapsed
### What happens?

https://github.com/user-attachments/assets/bb760c7f-73aa-4c49-8167-ecf884b87327

### What did you expect to happen?

We need to expand the section so it can be scrolled to.

### How can we reproduce the issue?

1. Add an internal link to an endpoint in the description markdown
2. While the section is collapsed, try to click the link.

### OpenAPI Document

_No response_

### PR DESCRIPTION
**Pull request by hwkr**
Make sure the section is expanded so we can scroll to it on hash change. Also adds some internal links to the Scalar Galaxy description.

Fixes #2603

## Before: 

https://github.com/user-attachments/assets/2309ab56-b83c-48db-8f02-e510782c557f

## After:

https://github.com/user-attachments/assets/574b62a1-82d4-4a24-890e-938c65a9ad74

### CODE REVIEW

File: packages/api-reference/src/components/ApiReferenceLayout.vue [hunk 1]
```diff
@@ -107,9 +108,15 @@ onBeforeMount(() => updateHash())
...
-
-  if (id) scrollToId(id)
-  else documentEl.value?.scrollTo(0, 0)
+  if (id) {
+    // Open the section if it's collapsed
+    const sectionId = getSectionId(id)
+    if (sectionId !== id && !isCollapsedSidebarItem(sectionId)) {
+      setCollapsedSidebarItem(getSectionId(id), true)
+      await sleep(100)
+    }
```
Comment (amritk) [inline packages/api-reference/src/components/ApiReferenceLayout.vue:117]:
```suggestion
      setCollapsedSidebarItem(getSectionId(id), true)
      await sleep(100)
```

tbh you can just set it to true, its just a hashmap

File: packages/api-reference/src/hooks/useSidebar.ts [hunk 2]
```diff
@@ -74,6 +74,10 @@ function setCollapsedSidebarItem(key: string, value: boolean) {
   collapsedSidebarItems[key] = value
 }
 
+function isCollapsedSidebarItem(key: string) {
+  return collapsedSidebarItems[key] ?? false
+}
+
```
Comment (amritk) [inline packages/api-reference/src/hooks/useSidebar.ts:80]:
```suggestion
```

File: packages/api-reference/src/hooks/useSidebar.ts [hunk 3]
```diff
@@ -360,6 +364,7 @@ export function useSidebar(options?: ParsedSpecOption & TagsSorterOption) {
     collapsedSidebarItems,
     toggleCollapsedSidebarItem,
     setCollapsedSidebarItem,
+    isCollapsedSidebarItem,
```
Comment (amritk) [inline packages/api-reference/src/hooks/useSidebar.ts:367]:
```suggestion
```

**Review by amritk — APPROVED** [review]
so this will probably work 99% of the time and we do it everywhere already.

However, if you want to do the correct (new) way: we use mutation observer to detect when the element has loaded then scroll to it. 

But I'll approve this one and let you decide what you want to do as its not really a blocker

File: packages/api-reference/src/components/ApiReferenceLayout.vue (hunk 1 above)
Comment (hwkr) [reply packages/api-reference/src/components/ApiReferenceLayout.vue:117]: We need to confirm sectionId !== id otherwise it triggers sometimes when it shouldn't

**Review by hanspagel — APPROVED** [review]
Great work! Approving the changes to the Scalar Galaxy example. 🏄

**Review by marclave — APPROVED** [review]
