### PR TITLE
fix(api-reference): displays schema name in property heading

### LINKED ISSUE #5377: Response type is ignored: object instead of actual type
### What happens?

I generate an open API documentation and expose it via Scalar UI using the following NuGet packages:

```xml
<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.4" />
<PackageReference Include="Scalar.AspNetCore" Version="2.1.9" />
```

The problem is that the Scalar UI ignores the schema name in the responses (i.e. `array Device[]`), and shows `array object[]` instead. Although, the actual type presents in the generated documentation (see the OpenAPI Document below).

I tested the same file with the Swagger UI and it does show the correct schema.

Image

### What did you expect to happen?

I expect to see `array Device[]` instead of `array object[]` in responses if `Device` is referenced in the responses definition, e.g.:
```json
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Device"
                  }
                }
              }
            }
          }
        }
```

### OpenAPI Document

```json
{
  "openapi": "3.0.1",
  "info": {
    "title": "Foo | v1",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://localhost:5555/"
    }
  ],
  "paths": {
    "/Private/Audit/ExportAllDevices": {
      "get": {
        "tags": [
          "Audit"
        ],
        "description": "Exports all devices",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Device"
                  }
                }
              },
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Device"
                  }
                }
              },
              "text/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Device"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Device": {
        "required": [
          "isActive",
          "name"
        ],
        "type": "object",
        "properties": {
          "isActive": {
            "type": "boolean"
          },
          "name": {
            "type": "string"
          }
        }
      }
    }
  },
  "tags": [
    {
      "name": "Audit"
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by antlio**
**Problem**

currently only the type is displayed as property heading over schema name.

**Solution**

this pr displays schema name when available over type and fixes #5377.

| before | after |
| -------|------|
| image | image |

**Checklist**

I’ve gone through the following:

- [x] I’ve added an explanation _why_ this change is needed.
- [x] I’ve added a changeset (`pnpm changeset`).
- [x] I’ve added tests for the regression or new feature.
- [ ] I’ve updated the documentation.

### CODE REVIEW

**Review by hanspagel — APPROVED** [review]
niice

File: packages/api-reference/src/components/Content/Schema/SchemaPropertyHeading.vue [hunk 1]
```diff
@@ -40,6 +50,27 @@ const flattenDefaultValue = (value: Record<string, any>) => {
...
+    return null
+  }
+
+  if (schema.name) {
+    return schema.name
+  }
+
+  if (schemas && typeof schemas === 'object') {
+    for (const [schemaName, schemaValue] of Object.entries(schemas)) {
+      if (JSON.stringify(schemaValue) === JSON.stringify(schema)) {
```
Comment (hanspagel) [inline packages/api-reference/src/components/Content/Schema/SchemaPropertyHeading.vue:66]: wait, those can have circular reference! that will break

**Review by hanspagel — CHANGES_REQUESTED** [review]

File: packages/api-reference/src/components/Content/Schema/SchemaPropertyHeading.vue (hunk 1 above)
Comment (antlio) [reply packages/api-reference/src/components/Content/Schema/SchemaPropertyHeading.vue]: great catch, fixed

**Comment by cyclr-adrian** [comment]
Speedy work!  When can I expect this fix to make it into the .net nuget package?

**Review by amritk — APPROVED** [review]
lgtm
