### PR TITLE
fix(api-client): apply multipart encoding content types

### LINKED ISSUE #7638: encoding.contentType not applied in multipart/form-data requests
### Discussed in https://github.com/scalar/scalar/discussions/7636

<div type='discussions-op-text'>

<sup>Originally posted by **tabago** January  6, 2026</sup>
Scalar API client is not respecting the encoding.contentType specification in OpenAPI 3.0 for multipart/form-data requests, resulting in parts being sent with incorrect Content-Type headers.

Expected Behavior
When an OpenAPI specification includes encoding with contentType:
```yaml
  yamlrequestBody:
    content:
      multipart/form-data:
        schema:
          type: object
        properties:
          user:
            type: string
            format: json
          file:
            type: string
            format: binary
      encoding:
        user:
          contentType: application/json;charset=utf-8
```

The user part should be sent with Content-Type: application/json;charset=utf-8.

Actual Behavior

Scalar sends the user part with Content-Type: application/octet-stream, ignoring the encoding specification.
Generated curl from Scalar:

```bash
--form 'user={"key":"value"}'  # Missing ;type=application/json
```

Expected curl:
```bash
--form 'user={"key":"value"};type=application/json'
```

## Impact

This causes server-side parsing failures when the backend expects JSON data:
```
org.springframework.web.HttpMediaTypeNotSupportedException: 
Content-Type 'application/octet-stream' is not supported

```
Comparison

✅ Swagger UI: Correctly applies encoding.contentType and sends with proper Content-Type
❌ Scalar: Ignores encoding.contentType specification

i dont know scalar ui
Please add support for the encoding.contentType field in OpenAPI 3.0 specifications for multipart/form-data requests.

</div>

### PR DESCRIPTION
**Pull request by AbdelhamidKhald**
Fixes #7638.

## Summary

Scalar now applies `encoding.contentType` for multipart request parts in both the request send path and the curl code sample path.

## Changes

- apply multipart `encoding.contentType` overrides when building the v2 `FormData` request body
- preserve explicit multipart part content types in HAR generation for example rows and schema-derived object parts
- render multipart curl snippets with `;type=...` for both file and non-file parts
- add patch changesets for `@scalar/api-client` and `@scalar/snippetz`

## Testing

- `pnpm exec biome check packages/api-client/src/v2/blocks/operation-block/helpers/build-request-body.ts packages/api-client/src/v2/blocks/operation-block/helpers/build-request-body.test.ts packages/api-client/src/v2/blocks/operation-code-sample/helpers/operation-to-har/process-body.ts packages/api-client/src/v2/blocks/operation-code-sample/helpers/operation-to-har/process-body.test.ts packages/snippetz/src/plugins/shell/curl/curl.ts packages/snippetz/src/plugins/shell/curl/curl.test.ts`
- `pnpm exec vitest run packages/api-client/src/v2/blocks/operation-block/helpers/build-request-body.test.ts packages/api-client/src/v2/blocks/operation-code-sample/helpers/operation-to-har/process-body.test.ts packages/snippetz/src/plugins/shell/curl/curl.test.ts`

### CODE REVIEW

File: packages/snippetz/src/plugins/shell/curl/curl.ts [hunk 1]
```diff
@@ -112,11 +112,12 @@ export const shellCurl: Plugin = {
...
           if (param.fileName !== undefined) {
-            const escapedFileName = escapeSingleQuotes(param.fileName)
+            const escapedFileName = escapeSingleQuotes(`${param.fileName}${multipartValueSuffix}`)
             parts.push(`--form '${escapedName}=@${escapedFileName}'`)
           } else {
-            const escapedValue = escapeSingleQuotes(param.value ?? '')
+            const escapedValue = escapeSingleQuotes(`${param.value ?? ''}${multipartValueSuffix}`)
             parts.push(`--form '${escapedName}=${escapedValue}'`)
           }
         })
```
Comment (hanspagel) [inline packages/snippetz/src/plugins/shell/curl/curl.ts:123]: we might want to update all plugins?

Comment (AbdelhamidKhald) [reply packages/snippetz/src/plugins/shell/curl/curl.ts:123]: Expanded this across the multipart generators that can preserve per-part content types without changing request semantics: guzzle, requests/httpx, csharp/fsharp httpclient, raw HTTP, and reqwest. I left fetch-style/php-curl style generators alone for now because typed string parts there need a bigger representation change.
