### PR TITLE
fix(api-reference): `onDocumentSelect` is not called

### LINKED ISSUE #7452: `onDocumentSelect` hook not firing
### What happens?

i'm using the AspNetCore integration of scalar (version 2.11.0) and when using the following custom javascript configuration
```js
export default {
    onLoaded: () => console.log("AAAA"),
    onDocumentSelect: () => console.log("BBBBB")
}
```
the `onDocumentSelect` hook is never triggered

### What did you expect to happen?

The `onDocumentSelect` hook is triggered and every time I select a different document "BBBBB" is printed to the console.

### OpenAPI Document

Not relevant

### PR DESCRIPTION
**Pull request by marcalexiei**
## Problem

- Closes #7452

## Solution

Here’s a clearer, more polished version:

- Invoke `onDocumentSelect` inside the `changeSelectedDocument` handler
- `await` both the `onDocumentSelect` and `onLoaded` hooks (their schemas allow them to return a `Promise`).
   https://github.com/scalar/scalar/blob/61c980cebef219685a05f3a4cb1e379984922cd4/packages/types/src/api-reference/api-reference-configuration.ts#L135-L142 
   https://github.com/scalar/scalar/blob/61c980cebef219685a05f3a4cb1e379984922cd4/packages/types/src/api-reference/api-reference-configuration.ts#L144
- Update the documentation for the `onDocumentSelect` and `onLoaded` hooks to indicate that they may return a `Promise`.

## Checklist

- [x] I explained why the change is needed.
- [x] I added a changeset. 
- [x] I added tests.
- [x] I updated the documentation.

### CODE REVIEW

File: packages/api-reference/src/components/ApiReference.vue [hunk 1]
```diff
@@ -470,7 +472,8 @@ const changeSelectedDocument = async (
             config: mapConfiguration(config),
           },
     )
-    config.onLoaded?.(slug)
+
+    await config.onLoaded?.(slug)
```
Comment (hanspagel) [inline packages/api-reference/src/components/ApiReference.vue]: the await makes those calls block the further execution, right? is that really what we want here? I think they should be executed asynchronously as long was we don’t need the result of the function.

**Review by hanspagel — CHANGES_REQUESTED** [review]

File: packages/api-reference/src/components/ApiReference.vue (hunk 1 above)
Comment (marcalexiei) [reply packages/api-reference/src/components/ApiReference.vue]: I refined the logic so both hooks invoke their handlers without blocking. 
I also ensured that `onLoaded` is triggered only after `onDocumentSelect` has finished (added a new test case).

https://github.com/scalar/scalar/pull/7459/commits/d8720297543c9fc826d4d0caff997e07eb5b8c33
