### PR TITLE
fix(api-client): doesn’t use the proxy properly to import from URLs, fix #3668

### LINKED ISSUE #3668: proxy doesn't follow relative redirects
Example: https://proxy.scalar.com/?scalar_url=https%3A%2F%2Falpha.api.worknet.ai%2Fdocs%2Fv1

Response Header: `Location: /docs/v1/`

Redirected to: `https://proxy.scalar.com/docs/v1/`

### PR DESCRIPTION
**Pull request by hanspagel**
Allows to import from way more URLs by properly using the proxy and extending `@scalar/import`  :)

## Release Notes

- **New Features**
	- Enhanced import functionality to support a wider range of sources and improved proxy utilization.
	- Introduced a modal for detailed error presentation in the import process.

- **Bug Fixes**
	- Streamlined error handling in the `ImportCollectionModal` and `PrefetchError` components.

- **Refactor**
	- Updated the `resolve` function to allow custom fetch options, improving flexibility in URL handling.

- **Tests**
	- Added new test cases for verifying embedded OpenAPI document URLs in various formats.

- **Chores**
	- Updated dependencies across multiple packages to enhance overall functionality.

### CODE REVIEW

**Comment by hanspagel** [comment]
@coderabbitai review

**Comment by hanspagel** [comment]
@coderabbitai full review

File: packages/api-client/src/components/ImportCollection/ImportCollectionModal.vue [hunk 1]
```diff
@@ -146,78 +145,87 @@ onUnmounted(() => {
...
-            <!-- <OpenAppButton :source="source" /> -->
-            <ImportNowButton
-              :source="prefetchResult?.url ?? source"
-              variant="button"
-              :watchMode="watchMode"
-              @importFinished="() => $emit('importFinished')" />
+        <template v-if="prefetchResult.error">
+          <!-- Heading -->
+          <div class="text-center text-md font-bold mb-2 line-clamp-1">
+            Missing OpenAPI document
```
Comment (antlio) [inline packages/api-client/src/components/ImportCollection/ImportCollectionModal.vue:151]: What do you think about

```suggestion
            No OpenAPI document found
```

File: packages/api-client/src/components/ImportCollection/PrefetchError.vue [hunk 2]
```diff
@@ -1,40 +1,53 @@
...
+      class="text-sm break-words text-center w-full font-medium">
+      We couldn't find an OpenAPI document at this URL. You can try visiting
+      <a
+        class="max-w-[50ch] truncate"
+        :href="result.input"
+        rel="noopener nofollow"
+        target="_blank"
+        v-text="domain" />
+      to download the OpenAPI file manually.
+    </div>
```
Comment (antlio) [inline packages/api-client/src/components/ImportCollection/PrefetchError.vue:39]: what do you think about leading to the action?

```suggestion
      We couldn’t find an OpenAPI document at the provided URL. Please import the
      <a
        class="max-w-[50ch] truncate"
        :href="result.input"
        rel="noopener nofollow"
        target="_blank"
        v-text="domain" />
      OpenAPI document manually.
    </div>
```

and then add the `Import Collection` that would open the import modal?

Comment (hanspagel) [reply packages/api-client/src/components/ImportCollection/PrefetchError.vue:39]: Screenshot 2024-10-30 at 14 28 41

File: packages/api-client/src/components/ImportCollection/ImportCollectionModal.vue (hunk 1 above)
Comment (hanspagel) [reply packages/api-client/src/components/ImportCollection/ImportCollectionModal.vue:151]: Screenshot 2024-10-30 at 14 30 25

**Comment by amritk** [comment]
Last time this wasn't working for yaml. can we confirm that it is this time? Haven't tried it yet

**Comment by hanspagel** [comment]
Ah, yeah. Last time I’ve added the import package to fetchSpecFromUrl which is used everywhere and I thought it’s cool that you use whatever URL in the reference configuration, but

1. The helper had multiple issues, so it was dumb to use it everywhere.
2. The URL in the configuration should be exact and not something that we need multiple fetch calls to resolve.

This time only the import modal tries to make sense of whatever input it gets, even if it involves fetching it through the proxy, retrying without the proxy, parsing the HTML … and also new this PR, the result of this process is then imported to the client, not the input. So it’s not necessary to have this heavy logic everywhere anymore.

:)

File: packages/api-client/src/components/ImportCollection/hooks/useUrlPrefetcher.ts [hunk 3]
```diff
@@ -12,34 +18,96 @@ export type PrefetchResult = {
  * Core logic for fetching and processing a URL
  */
 export function createUrlPrefetcher() {
```
Comment (amritk) [inline packages/api-client/src/components/ImportCollection/hooks/useUrlPrefetcher.ts:20]: I'm not sure I understand why this is a factory? Can't we just use prefetchUrl directly?

Comment (amritk) [reply packages/api-client/src/components/ImportCollection/hooks/useUrlPrefetcher.ts:20]: maybe I'm missing something 😕

File: packages/api-client/src/components/ImportCollection/hooks/useUrlPrefetcher.ts [hunk 4]
```diff
@@ -12,34 +18,96 @@ export type PrefetchResult = {
...
-  async function prefetchUrl(value: string | null, proxy?: string) {
-    if (!value || typeof value !== 'string') {
-      return { state: 'idle', content: null, url: null, error: null }
+  async function prefetchUrl(input: string | null, proxy?: string) {
+    if (!input || typeof input !== 'string') {
```
Comment (amritk) [inline packages/api-client/src/components/ImportCollection/hooks/useUrlPrefetcher.ts:22]:
```suggestion
    if (!input || typeof input !== 'string') {
```
redundant check since !input should catch null as well

File: packages/import/package.json [hunk 5]
```diff
@@ -44,7 +44,8 @@
   ],
   "module": "dist/index.js",
   "dependencies": {
-    "@scalar/openapi-parser": "workspace:*"
+    "@scalar/openapi-parser": "workspace:*",
+    "yaml": "^2.4.5"
```
Comment (amritk) [inline packages/import/package.json:48]: I knew it!

**Review by amritk — APPROVED** [review]
Not sure I fully understand this one, but tested and its working!

Maybe just some jsdoc examples is all we need!

**Review by hwkr — APPROVED** [review]
Gave it a test and worked for me!

File: packages/import/package.json (hunk 5 above)
Comment (hanspagel) [reply packages/import/package.json:48]: This is only used to parse yaml from HTML though 😛

File: packages/api-client/src/components/ImportCollection/hooks/useUrlPrefetcher.ts (hunk 4 above)
Comment (amritk) [reply packages/api-client/src/components/ImportCollection/hooks/useUrlPrefetcher.ts:22]: redundant suggestion as I forgot to change it

File: packages/api-client/src/components/ImportCollection/hooks/useUrlPrefetcher.ts (hunk 3 above)
Comment (hanspagel) [reply packages/api-client/src/components/ImportCollection/hooks/useUrlPrefetcher.ts:20]: True! It was necessary before, but not anymore. Let’s keep it simple. 👍
